### ISSUE TITLE
New folder button when saving a file

### ISSUE THREAD

**Issue by nicolafan** [Akuli/porcupine#1003]
It would be useful to have the possibility of creating a new folder in the current space when we are saving a file:
![Screenshot from 2021-12-15 14-26-26](https://user-images.githubusercontent.com/48762613/146195483-cbee8bdb-92b3-4191-9be7-47e1fdecfe07.jpg)
This could be done with a button on the top right.

**Comment by Akuli** [comment]
Porcupine uses Tk's file dialogs as is. Modifying these dialogs would be quite difficult, and is platform-specific at best, so this is a similar situation as #820. We could change the dialog in Tk itself, but it would take an eternity to get the changed Tk in the apt repositories.

**Comment by nicolafan** [comment]
![Uploading t2{edb2a27} (5980f465-7554-42cb-b284-55961edee2da id=0x7f0a03a0) …]()
Ohh Idk why the other time I understood that only the selector was provided directly by Tk 😅. Thank u, I'm closing tthe issue.
