### ISSUE TITLE
wiki: screenshot is outdated

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1005]
https://github.com/Akuli/porcupine/wiki/Working-with-projects

The screenshot shows a terminal that contains `/home/akuli/porcu/env/bin/python foo.py` printed in blue. In newer versions, `env/bin/activate` is sourced first, instead of calling the venv's python directly.

**Comment by rdbende** [comment]
https://github.com/Akuli/porcupine/wiki/First-Program:

![image](https://user-images.githubusercontent.com/77941087/180807036-53570c96-1819-4b05-830a-e55da33cbb37.png)

**Comment by Akuli** [comment]
Wiki was deleted.
