### ISSUE TITLE
Update Virtual Events documentation

### ISSUE THREAD

**Issue by Kawaritai** [Akuli/porcupine#1028]
TODO: Update Virtual Events documentation to explain the association of certain virtual events with physical events (i.e. non-virtual events like `<App>` or `<Button-2>`), defined in the file `default_keybindings.tcl`. 
Where to find the documentation: 
https://akuli.github.io/porcupine/plugin-intro.html#virtual-events
`docs\plugin-intro.rst`      (To find it, you can e.g. search for its title "Virtual Events" in all files, e.g. `git grep "Virtual Events"`.)

**Comment by Akuli** [comment]
This is now documented in the docstring of `porcupine/menubar.py`. Not an ideal place, but this might get changed and better documented "soon".
