### ISSUE TITLE
Weird syntax highlight inside #if 0 at scrolling

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#1038]
Syntax highlighting is weird inside `#if 0`

https://user-images.githubusercontent.com/77941087/158164580-85837412-f259-4267-82fe-0617e5b3ec06.mp4

I think it's because of the visible-area-tracker-thingy in `highlight.py`

**Comment by Akuli** [comment]
(Side note: GtkTtk sounds interesting)
