### ISSUE TITLE
jump to definition delay

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1041]
Sometimes it takes a very long time (e.g. between 30sec and 60sec) for a langserver to compute a location after your Ctrl+click something. By the time it's done, I have forgotten about what I was trying to do when ctrl+clicking, and it would be nice if Porcupine wouldn't jump to the location that the langserver suggests.

**Comment by benjamin-kirkbride** [comment]
Dupe of https://github.com/Akuli/porcupine/issues/1012 ?

**Comment by Akuli** [comment]
It is :)
