### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1066]
Should figure out why tests fail on VideoCarp's computer (#1065).
- Alt+F4 tests: The tests are supposed to ensure that pressing Alt+F4 closes the Porcupine window. @videocarp Does it work for you?
- rstrip plugin: No idea why this fails. @VideoCarp If you write some text into Porcupine and put a bunch of spaces at the end of the line, do the spaces get erased
- venv tests: Creating venvs fails for some reason. This has nothing to do with Porcupine, so I'll just mark the tests with xfail (expected failure).

**Comment by VideoCarp** [comment]
Alt + F4 does close the Porcupine window. And it gives a warning to save.
The spaces do get erased.
And I have a hypothesis for the issue with `venv`s. For some reason, I get fatal error when doing any Python commands without the `py` prefix. For example, I had to do `py -m black porcupine` as `black` resulted in a fatal error. This also happened with `pip`. So it's probably on my end for this one.

**Comment by Akuli** [comment]
Thanks! I'll silence the Alt+F4 and venv tests next.

I still don't know what's going on in the rstrip test. What happens if you copy the `intense_super_update()` function from test_jump_to_definition_plugin.py to `test_rstrip_plugin.py` and use it instead of `filetab.update()`?

**Comment by Akuli** [comment]
When you create a venv, Python creates a bunch of `.exe` files inside `env\Scripts\`. When you activate a venv, this folder is added to your PATH so that when you type e.g. `pip` or `black`, it runs `env\Scripts\pip.exe` or `env\Scripts\black.exe`. This is how venvs work.

To me, it sounds like your Windows just refuses to run any `.exe` files inside the venv, maybe because Python created them. But `py -m` helps, because there's no `env\Scripts\py.exe`, and so `py` really means `C:\Windows\system32\py.exe` which your Windows can run.

**Comment by Akuli** [comment]
Nothing can really be done for a very old issue on someone else's computer. If something is still broken, someone else will create a new issue.
