### ISSUE TITLE
pressing enter should open file

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1076]
Directory tree is the thing at left. For example, if it looks like this:

![s](https://user-images.githubusercontent.com/18505570/193363107-b50da718-73a4-416c-be58-1066910591bb.png)

you can press the right arrow key to see what's in the `porcupine` folder. Or if you select a file instead, right arrow key opens it in Porcupine. Pressing Enter works too.

If you select a file instead of a folder, the arrow key opens the file in Porcupine, but pressing enter does nothing. It should do the same thing as the right arrow key.

<details><summary>Reasons why supporting the enter key would be good</summary>

- ~Today~ A while ago I disabled my arrow keys to strain my right hand less. I now have to double-click with the mouse.
- Enter is likely more discoverable for people new to porcupine.
- Enter already opens folders.

</details>

Relevant files:
- `porcupine/plugins/directory_tree.py` creates the directory tree
- (might not need this file: ) `porcupine/default_keybindings.tcl` is a Tcl file that runs when Porcupine starts, and it defines names for various key presses.

**Comment by Moosems** [comment]
I can look into this
