### ISSUE TITLE
Porcupine discord?

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1096]
I have been thinking about making a Discord server or something else like that for Porcupine development. GitHub issues and PR comments are great for long messages that have to be around for weeks or years, but it would be good to also have something that encourages writing short messages while working together. I have developed several projects with friends this way, and it's been great: sometimes we debug something on the chat for several hours, and everything that ends up on GitHub is concise and to the point.

I have used IRC for this in the past, but because all Porcupine developers seem to be quite young, I think I am the only one of us who knows what IRC is. I also use Discord, so we could use it if everyone else is happy with it.

@rdbende and @Moosems, what do you think?

**Comment by rdbende** [comment]
To be honest, I'm more an IRC, than a Discord person.
I'm not really familiar with IRC commands, and I don't use it often (though I'm often on ##learnpython lately), but it was a mandatory topic for the informatics graduation, so you're not the only one who knows what it is :)
I don't use Discord, but that's also fine for me.

**Comment by Akuli** [comment]
I guess we'll just use IRC then :) If it turns out later that someone wants to use discord or something else, I'm fine with that too, but I don't think we should create any kind of group chat (that we wouldn't use) until we have at least 3 people sending messages on the same platform.

**Comment by Moosems** [comment]
> I have used IRC for this in the past, but because all Porcupine developers seem to be quite young, I think I am the only one of us who knows what IRC is.

What exactly is IRC? I've used the internet for quite a while but haven't heard of IRC

**Comment by Akuli** [comment]
IRC is probably the oldest "chat" kind of thing that is still being used. You write text to a channel, other people on the channel see it.

Under the hood, IRC is super simple, so it's easy to write custom IRC bots or clients without using IRC-specific libraries. For example, with Discord you typically install something like `discord.py` to write a bot, and writing a custom client seems to be impossible. In IRC both are possible, and you don't need to install anything if you already have Python.

The easiest way to get started is probably to click "Help --> Python --> Free help chat" in Porcupine. This opens a web-based IRC client in your browser and joins a channel where I and rdbende are regularly.

**Comment by Moosems** [comment]
How can I do you in it?

**Comment by Akuli** [comment]
We seem to be online at different times. Your previous comment was sent at 2:05 AM in my timezone, and I am usually not awake at that time. I'm on IRC now and I will leave in a couple hours.

Now I can answer your question:
- If we are online at the same time, you can type `/msg Akuli blah blah` where `blah blah` is the message you are sending to me. This will work regardless of what client you use to connect to IRC. Most clients also have their own way to do the same thing, e.g. right-clicking my name in the user list or something.
- If we are online at different times, the command is `/msg memoserv send Akuli blah blah`. This tells a bot named `memoserv` to deliver your message to me when I appear online again. But if you find yourself actually doing this, I think it would be easier to use something else than IRC :)

IRC doesn't "remember" messages like other newer chat services do: if you wrote something while I was not connected to IRC, I won't see your message. That's why the `memoserv` bot is needed.
