### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1099]
Here are some thoughts about the next release.

I made a new, better syntax highlighter for Porcupine that doesn't work with as many languages as Pygments, but it fixes many pygments-related problems (#216, #434, #435, #995, #1032, #1038). I still need to figure out how to get it to work on Windows and MacOS, and also how to get it to automatically set itself up instead of having to run a script before you can use Porcupine. Should we get it to the next release or the one after that, as there's quite a lot of other improvements too?

I think the next release number will be 0.100.0. I don't want to lock down the public API of Porcupine, which is what 1.x.y would mean in [semver](https://semver.org/). But I have also thought about switching to [calver](https://calver.org/).

**Comment by rdbende** [comment]
> the one after that

I think this would be better, according to `git log` we had 39 merged pr-s since 0.99.2, which was almost 8 months ago.

> switching to [calver](https://calver.org/)

I support this. For apps I've always preferred calver.

**Comment by Akuli** [comment]
Ok, let's get a calver release out before I work more on the new highlighter :)

I think I want to use the 4-digit year (2022) and not the two-digit year (22), because I remember being surprised when I learned that the first part of pip and ubuntu versions is a year. In other words, I think that two-digit years aren't intuitive to users because they don't look like years.

I think we should go with YYYY.MM.DD (e.g. Porcupine 2022.07.29), not YYYY.MM.micro (e.g. Porcupine 2022.07.0). This way the versioning is as obvious as it can be for users. A downside is that if a release is so broken that we want to do another release during the same day, we need to "cheat" and use the next day's version number. If this becomes a problem, we can later change to YYYY.MM.micro.

**Comment by rdbende** [comment]
> I think we should go with YYYY.MM.DD

👍

> first part of pip and ubuntu versions is a year.

Ubuntu was somehow obvious to me the first time, but I didn't realized that 22 in pip means 2022, until now lol. I don't usually check the version, just update it when it asks me to :D

**Comment by Akuli** [comment]
I released Porcupine and tested the Windows installer.
