### ISSUE TITLE
[Feature Request] different 'close' icon on tabs

### ISSUE THREAD

**Issue by Zaab1t** [Akuli/porcupine#11]
It looks odd IMO and doesnt work with any of the themes really. Might I suggest 'x' from https://feather.netlify.com/ :)

**Comment by Akuli** [comment]
I know that the x button sucks.

Some day I'll use the same close button that Windows uses when porcupine is running on windows (tcl has a thing for that), but if I'll add something nicer for linux users it'll definitely come from the user's icon theme of choice (somewhere in `/usr/share/icons`) with e.g. Gtk. Hard-coded icons suck in general, and switching to a different kind of icon doesn't help with that.

**Comment by Zaab1t** [comment]
I think the icon I suggested would be good enough for quite a while

**Comment by Akuli** [comment]
Can you suggest an icon with a non-transparent background? A black icon like the one you suggested wouldn't work very well with a dark ttk theme.

**Comment by theelous3** [comment]
[x.zip](https://github.com/Akuli/porcupine/files/1254400/x.zip)

**Comment by Zaab1t** [comment]
Everybody wins 🎉🎉🎉

**Comment by Akuli** [comment]
This would still be black on black with a dark ttk theme :expressionless:

**Comment by theelous3** [comment]
It has a semi-transparent white bg. Not sure you can see it. Perhaps it should be more opaque? tias :D

**Comment by Zaab1t** [comment]
Yes, this work on a black background for me.

**Comment by Akuli** [comment]
[Now it's fixed.](https://github.com/Akuli/porcupine/commit/031080d4a3e)
