### ISSUE TITLE
Sometimes command output is invisibly small

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1128]
You can stretch the output area to make it bigger or smaller. Porcupine even remembers its position when you restart, I think. But this can happen:
1. User wants to hide the output. Instead of pressing F4 (or clicking something in the menu), they just stretch it to be zero height, which is quite a reasonable thing to do.
2. Time goes on. User forgets what they did.
3. User wants to run a new command. The output area comes up with zero height.

When showing the output area for running a command, we should ensure it is never e.g. less than 100px tall.

**Comment by Moosems** [comment]
What if we based the minimum height off of the current font?

**Comment by ethical-haquer** [comment]
This actually happened to me! I just assumed that the built-in command output was broken, so I haven't use it.
