### ISSUE TITLE
Highlighting Python f strings

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1136]
![f](https://user-images.githubusercontent.com/18505570/184255057-7f863c41-f02e-447e-a030-f081902f4def.png)

Above is pygments highlighter, below is tree-sitter highlighter. It would be good if the tree-sitter highlighter recursed inside f-strings like the pygments highlighter does. This is important because otherwise you don't notice if you forget the `f` in front of the string.

**Comment by Akuli** [comment]
This will be quite tricky to fix:

```
(env) akuli@akuli-desktop:~/porcu$ cat asd.py 
f"{asd} + {len(url)} chars"
{}

(env) akuli@akuli-desktop:~/porcu$ python3 scripts/tree-sitter-dump.py python asd.py 
type=module text='f"{asd} + {l... chars"\n{}\n'
  type=expression_statement text='f"{asd} + {len(url)} chars"'
    type=string text='f"{asd} + {len(url)} chars"'
      type=" text='f"'
      type=interpolation text='{asd}'
        type={ text='{'
        type=identifier text='asd'
        type=} text='}'
      type=interpolation text='{len(url)}'
        type={ text='{'
        type=call text='len(url)'
          type=identifier text='len'
          type=argument_list text='(url)'
            type=( text='('
            type=identifier text='url'
            type=) text=')'
        type=} text='}'
      type=" text='"'
  type=expression_statement text='{}'
    type=dictionary text='{}'
      type={ text='{'
```

What I would like to do is to highlight `} + {` as a string, but that's really not how tree-sitter works:
- The `" + "` part is not available as a separate AST node anywhere. It's just a part of the f-string node, not a separate subnode of it.
- There are `{` and `}` subnodes at ends of the interpolation parts (`{asd}` and `{len(url)}`). But `{` and `}` nodes can also be dictionary syntax, as the `{}` at the end of `asd.py` shows.

**Comment by rdbende** [comment]
Got it working. Though the code is a boilerplate shit.

![image](https://user-images.githubusercontent.com/77941087/184378635-fc85a057-453a-4c24-b0a6-99955b6368d9.png)

**Comment by Akuli** [comment]
Maybe we could try to get tree-sitter's queries working in the token mappings before we add hacks for various corner cases.

**Comment by rdbende** [comment]
I don't think f-strings could be solved that way though.
The solution is eventually to highlight the entire f-string as a string, then recurse into it and highlight the rest, which have separate AST nodes. But IMO this solution introduces way too much hacky and Python-only code 😕

**Comment by Akuli** [comment]
Turns out that the queries are always recursive. There's no way to limit them to only apply to a certain part of the file (either visible part or just a string node would be enough for this). py-tree-sitter has `start_point` and `end_point` arguments, but they don't do anything when used, although this will be fixed in their next release.

I still have a couple ideas for how to get rid of the language-specific code in the highlighter plugin and also highlight f-strings :)
