### ISSUE TITLE
Tooltips for image buttons

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1139]
The run plugin creates these buttons. They appear when pressing F4 or running a command.

![s](https://user-images.githubusercontent.com/18505570/196025257-0b5c998d-d28b-4456-827a-9e22bd86b78d.png)

It would be nice if the pause button displayed e.g. "Pause execution" when hovered, and similarly for other buttons. A tooltip would be especially useful for the "X" button, because it isn't clear whether it deletes the output when clicked, but it would be clear if it had a tooltip saying "Hide output area" or similar.

The tooltips should match with what is in the Run menu, so:
- "Pause execution" or "Resume execution", depending on whether a process is running
- "Kill process"
- "Hide output"

To test these, just run a `.py` file that contains something like:
```python
import time
time.sleep(60)
```

Porcupine used to have code for creating tooltips, but it was a lot of code to maintain for only one tooltip in the whole Porcupine, so it was deleted in #610. We can revert that PR to get it back (and maybe edit the docstring to be slightly less opinionated towards idlelib).

**Comment by lawson89** [comment]
@Akuli I can take a shot at this one some time this week

**Comment by lawson89** [comment]
@Akuli @rdbende reverting the commit had a lot of merge conflicts. 
Is it ok for me to pull the code in by hand?
