### ISSUE TITLE
Update check on startup

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1141]
It would be nice if Porcupine notified its users **non-disruptively** when a new version is out. For example, it could show a message in the status bar when it starts, or when the first tab is opened if no tabs open on startup (because of the user's settings or because they had no tabs opened when closing Porcupine).

Querying the latest version from GitHub's API is quite straight-forward:

```
>>> import requests
>>> requests.get('https://api.github.com/repos/Akuli/porcupine/releases/latest', headers={'Accept': 'application/vnd.github+json'}).json()['tag_name']
'v2022.07.31'
```

**Comment by rdbende** [comment]
It could also be on the welcome screen.

**Comment by Akuli** [comment]
One problem with using the welcome screen is that some people look at it very rarely: they have the setting to remember tabs when Porcupine is closed and opened again. So if we use the welcome screen, it would be good to also use automatically opened tabs.

**Comment by Moosems** [comment]
Why not just use the status bar?

**Comment by Akuli** [comment]
There is no status bar when you have no tabs open.

**Comment by Moosems** [comment]
Ahh. So then just whichever one is open at start

**Comment by Moosems** [comment]
No tabs, there's the welcome page. Also, I'd love a global status bar for items related to the entire editor like reloading and so forth.
