### ISSUE TITLE
highlighting decorators

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1149]
Above pygments, below tree-sitter:
![g](https://user-images.githubusercontent.com/18505570/184537817-36cbaca7-28aa-4588-9ac8-b21248ba7245.png)

Pygments isn't perfect either here. Presumably the entire decorator should be highlighted in the same color: I am after all decorating with `contextlib.contextmanager`, not with `contextlib`.

If the decorator has an argument list, e.g. `@functools.wraps(blah)`, it should highlight the `(blah)` part as it would highlight it anywhere else, and only the `@functools.wraps` part should be decorator-colored (blue in this theme).

**Comment by rdbende** [comment]
```python
decorated_definition: |
  (decorated_definition
    (decorator
      ("@") @Token.Name.Decorator
      (identifier)? @Token.Name.Decorator
      (attribute)? @Token.Name.Decorator
      (call)? @recurse
    )
    definition: (_) @recurse
  )
```
I was too lazy to make a PR with it 😬
