### ISSUE TITLE
geometry plugin: remember whether window is maximized

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1176]
Steps to reproduce problem:

1. Maximize Porcupine window
2. Close Porcupine
3. Reopen Porcupine. It is no longer maximized, just really big so that it kinda looks maximized

Porcupine should presumably stay maximized when restarted. Apparently this is possible with `root.wm_attributes('-zoomed', bool_value)` and `root.wm_attributes('-zoomed')`, where `root` is the return value from `get_main_window()`. The relevant file is `porcupine/plugins/geometry.py`

**Comment by lawson89** [comment]
I tried to do this one but was unable to determine reliably if window was maximized. 

I did however find how to maximize (it differs by platform)
From: Alan Moore's book - Python GUI Programming with Tkinter

win/mac
`root.state('zoomed')`

linux
`root.attributes(-'zoomed', True)`

**Comment by rdbende** [comment]
You can use these same functions to query if it's maximized.

```python
# Windoze/MacOSX
is_maximized = (root.state() == "zoomed")

# GNU+Linux
is_maximized = bool(root.wm_attributes("-zoomed"))
```

**Comment by lawson89** [comment]
Thanks @rdbende

Working on PR now
