### ISSUE TITLE
Add rust example commands to default_filetypes.toml

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1192]
`default_filetypes.toml` contains, among other things, example commands for various programming languages. See the `[[Python.example_commands]]` sections for how they should look.

Currently rust has no example commands. They should be easy to add, because most rust users simply have `cargo` in their PATH and Porcupine doesn't need to do anything platform-specific to find it.

We should add at least these commands:

`cargo run`
`cargo test`
`cargo build`
`cargo clippy`
`cargo fmt`

I personally use the short versions of these commands commands (e.g. `cargo r` instead of `cargo run`), but using them as defaults in Porcupine would likely be more confusing than helpful.

**Comment by aloner-pro** [comment]
I can do this. Can you assign me these please.

**Comment by Akuli** [comment]
Fixed in #1205.
