### ISSUE TITLE
Testing the fullscreen plugin

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1196]
In #1194 I wrote tests for the full screen plugin, but they turned out to not be very useful because they don't work on github actions. On linux, this is because we use xvfb-run, and apparently whatever window manager xvfb emulates or uses doesn't know about full-screening.

This means that we need to check manually whether the fullscreen plugin works on all platforms. This is easy as clicking "View" --> "Toggle Full Screen" (or pressing F11) while Porcupine is running. (If you have "Full Screen" instead of "Toggle Full Screen", you need to `git pull` first.)

- [x] Tested on Windows
- [x] Tested on MacOS
- [x] Tested on Linux

**Comment by Akuli** [comment]
Tempting to mark this as hacktoberfest, but it wouldn't work because getting this done doesn't involve a pull request.

**Comment by rdbende** [comment]
"Toggle Full Screen" works well in both a Windows 11 and macOS Catalina VM.

**Comment by Akuli** [comment]
Thanks!
