### ISSUE TITLE
[Feature Request] Minimap plugin

### ISSUE THREAD

**Issue by carlbordum** [Akuli/porcupine#12]
Like the popular one for Sublime Text, Atom, VS Code etc

**Comment by Akuli** [comment]
I have never used these editors. What does it do? A file browser?

**Comment by Akuli** [comment]
Is it one of these tiny-tiny-font overviews of a long code? Geany just calls it "overview". I think I can do something like this.

**Comment by Zaab1t** [comment]
Yes it is :)

**Comment by Akuli** [comment]
Is it ok to use a hard-coded font size (e.g. 2px)?

**Comment by Akuli** [comment]
Quick and dirty test. Run with porcupine in `sys.path`.

```python
import tkinter
import tkinter.font as tkfont

from porcupine.textwidget import HandyText


def on_content_changed(event):
    # TODO: keeping the same content in two places sucks, and updating
    # it all when only a single character might have changed sucks even
    # more :(
    text2['state'] = 'normal'
    text2.delete('1.0', 'end')
    for chunk in text1.iter_chunks():
        text2.insert('end', chunk)
    text2['state'] = 'disabled'


root = tkinter.Tk()

family = tkfont.Font(name='TkFixedFont', exists=True).actual('family')

text1 = HandyText(root)
text1.pack(side='left', fill='both', expand=True)
text1.bind('<<ContentChanged>>', on_content_changed, add=True)
text2 = HandyText(root, font=(family, 1, ''), state='disabled')
text2.pack(side='left', fill='y')

root.mainloop()
```

What do you think?

**Comment by Zaab1t** [comment]
Don't think I'm running it correctly. It runs, shows me a text field and "something" on the right side of the screen but that something doesnt seem to do anything.

**Comment by Akuli** [comment]
What do you want it to "do"?

**Comment by Akuli** [comment]
Now there is an implementation of this on the `langserver` branch, and clicking the overview (or minimap or whatever you want to call it) scrolls to the clicked part of the file. Also, it doesn't keep the content of the file being edited in two places anymore. Try it and let me know what you think.

**Comment by PurpleMyst** [comment]
If you mentor me a bit I think I can integrate the langserver into the minimap. VS Code shows lines with warnings/errors highlighted, like this:

![Minimap Image](https://files.catbox.moe/s4yklb.png)

**Comment by Akuli** [comment]
Maybe instead show the errors on the scrollbar, since the scrollbar always shows the entire file even though the file might be so long that it doesn't fit into the minimap? Or if both plugins are loaded, add an option for showing them in overview to the setting dialog? The scrollbar is just a widget, so we can `place` any other widgets on top of that, such as a frame with a custom background color.

**Comment by Akuli** [comment]
The find plugin highlights the things it has found, so maybe show them in scroll bar or overview too? More generally, everything that creates tags with a custom background color?

**Comment by Akuli** [comment]
This is currently implemented on the `langserver` branch, and I'll close this issue when that goes to master

**Comment by Akuli** [comment]
porcupine 0.71 has this
