### ISSUE TITLE
Plugin manager shouldn't be a plugin

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1208]
Disabling all plugins in the plugin manager (Settings menu at top, Plugin Manager, press Ctrl+A, click "Disable") is annoying, because it asks whether you also want to disable the plugin manager. You probably don't, because if you disable it, the only way to get it back is to edit a `.json` file by hand.

To fix this, the plugin manager shouldn't be a plugin. Specifically, we should:
- Move `porcupine/plugins/pluginmanager.py` so that it is not in the `plugins` folder
- Delete `setup()` function in that file (a function named `setup()` is called when a plugin is loaded, see https://akuli.github.io/porcupine/plugin-intro.html )
- The `setup()` function only adds the menu item to the Settings menu. We should do that somewhere else during Porcupine startup, probably `_fill_menus_with_default_stuff()` in `menubar.py`.

**Comment by aloner-pro** [comment]
Wouldn't deleting `setup()` function cause problems?

**Comment by aloner-pro** [comment]
Where should we exactly move `pluginmanager.py`?

**Comment by aloner-pro** [comment]
Also once the `pluginmanager` starts there doesn't seem to be any way to exit it. I had to exit the whole program to remove that window.

**Comment by Akuli** [comment]
`pluginmanager.py` would be just outside the plugins folder (because it's not a plugin) but inside the `porcupine` folder (because it is a part of porcupine), similar to e.g. `menubar.py`. You can close the plugin manager from the x button in top right corner.

**Comment by aloner-pro** [comment]
So I am working on this. Can you assign me this?
