### ISSUE TITLE
Plugin Idea: Full Integrated Terminal

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1209]
I believe this wouldn't be too difficult outside of making modifications to the run plugin. All it would need is allowing the user to make commands and actually deal with the terminal interface instead of being limited to output or in the case of the debugger, being able to exit, change directories, and so on.

**Comment by rdbende** [comment]
> full integrated terminal?

Why don't use your real terminal then?

**Comment by rdbende** [comment]
Yeah, I know. The macOS terminal is a piece of garbage.
But usually I use KDE apps, which have all the functionality that I could need, and all my other apps are terminal-based. So in my opinion if something makes clutter, than it's when those "all other apps" are integrated into a text editor. I think here the Unix philosophy ("do only one thing, but do that one thing well") is more suitable.

**Comment by Moosems** [comment]
😆 Yeah it is pretty garbage. I love the design of the terminal in VS Code and always hated Atom for not having one. The run plugin in porcupine is essentially the idea just the ability to give input and do commands in it would be all it needs

**Comment by Moosems** [comment]
The great part about an integrated terminal is that its there if you want it (for people like me) and you don't actually *have* to use it, for people like you. Its a win win :D.

**Comment by Akuli** [comment]
There used to be a terminal plugin, but nobody used it because it was buggy. Getting it to work nicely would be possible, but difficult, and there would be lots of platform-specific gotchas. So I don't really want it in Porcupine, *even if* someone else writes it initially.

**Comment by Moosems** [comment]
Where would I find the old one? I want to make an actually decent one ([tkterminal](www.github.com/saadmairaj/tkterminal) is something I used to use but is unmaintained and could use some hefty work) because I feel it would improve a lot of tk text editors.

**Comment by Akuli** [comment]
As I said, I'm not going to pour much effort into this, so you'll need to search the git history yourself. It was in `more_plugins` (which no longer exists).

**Comment by Moosems** [comment]
Can I ask a quick question that popped up when looking at the code for the terminal, how exactly does the `container=True` work in tkinter? I checked the man pages and not much came up and, though I couldn't find much documentation on it, it seems you understood how to use it to put an external application inside a Frame.

**Comment by Akuli** [comment]
I copied it from stackoverflow. I understand the idea about as much as the manual page explains it.

**Comment by rdbende** [comment]
```py
frame = tkinter.Frame(root, container=True)
# container=True indicates, that an external window can be embedded into this frame

frame.pack()

top = tkinter.Toplevel(root, use=frame.winfo_id())
# A Tk toplevel can be embedded into a frame with the `use` kwarg
```

Note 1: I'm not sure whether this feature works at all outside X11

Note 2: Not every application can be embedded into another window. In this case, `xterm` supports it with the `-into` option, but I'm pretty sure I couldn't embed ohter terminal emulators this way.
