### ISSUE TITLE
Tooltips go off-screen

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#1224]
![image](https://user-images.githubusercontent.com/77941087/204140362-e166f02b-9c9d-42a9-9077-9586cc052a38.png)

**Comment by Moosems** [comment]
You can borrow the placement code from DIP's tooltip, I developed it with Akuli so I hope it lives up to his standards.

**Comment by Akuli** [comment]
yes, I like how simple we eventually got DIP's tooltip logic :)

Though for these tooltips it could be even simpler. We could e.g. always show the tooltip above and to the left, there's always room.

**Comment by Moosems** [comment]
Thank you for your help with that by the way, it was tremendously useful.

**Comment by lawson89** [comment]
I can grab this one - I'll submit a PR by end of day today for review
