### ISSUE TITLE
Black in `requirements.txt`

### ISSUE THREAD

**Issue by taahol** [Akuli/porcupine#1240]
https://github.com/Akuli/porcupine/blob/84d502bc9bf272915309a535b54a181397d76e01/requirements.txt#L8

Is it really needed there (that is, not only in `requirements-dev.txt`)?

**Comment by rdbende** [comment]
There's the `python_tools` plugin, that uses it.

**Comment by taahol** [comment]
OK, that will explain the line. Thanks!
