### ISSUE TITLE
more_plugins should be deleted

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1271]
nobody uses it

**Comment by Moosems** [comment]
I do... when I use porcupine that is.

**Comment by Moosems** [comment]
The old Tetris plugin 🤣.

**Comment by Akuli** [comment]
You can still continue using the tetris plugin and any other plugins you have in *your* plugin directory, even when the `more_plugins` folder is deleted.

Porcupine doesn't do anything with the `more_plugins` folder. It doesn't even look for plugins there. To use plugins from `more_plugins`, you need to manually copy them to your plugins folder. It has always been this way.
