### ISSUE TITLE
run plugin: possible to backspace previous input

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1273]
To reproduce, press Shift+F5 and type `python3 -i` as the command. This runs an interactive Python shell. Then type a command (say `import tkinter`), and navigate to the start of the last line.

![s](https://user-images.githubusercontent.com/18505570/231898053-b1eeb09c-9b54-4f7d-b490-7c4356d48c5d.png)

Now press backspace.

Expected result: nothing happens
Actual result: mess

**Comment by rdbende** [comment]
Not just the last line, but every prompt line except the first.

**Comment by Moosems** [comment]
I can still delete the prompt even after pulling...

**Comment by Moosems** [comment]
https://user-images.githubusercontent.com/95927277/234112963-933fc9a9-c875-4388-98c5-8a707a5ba7de.mov

**Comment by Akuli** [comment]
This issue is about the command running area, not the debug prompt. But you're right that the debug prompt has the same bug.
