### ISSUE TITLE
Tree-sitter

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1279]
Why not take all the languages mentioned on the site, build them as `.so` files, and then load the builds? This would allow more languages to be added relatively easily though `HTML` would be a challenge to add due to its `JavaScript` referencing.

**Comment by Akuli** [comment]
If I understand you correctly, you mean something like https://github.com/Akuli/py-tree-sitter-builds which Porcupine already uses.

**Comment by Moosems** [comment]
Not quite, I mean loading a compiled file for the language parser.

**Comment by Akuli** [comment]
Porcupine already does that. That's how py-tree-sitter-builds works.

**Comment by Moosems** [comment]
> Porcupine already does that. That's how py-tree-sitter-builds works.

Not as a `.so` file.

**Comment by Moosems** [comment]
https://github.com/tree-sitter/py-tree-sitter#:~:text=build%60%20directory%0A%20%20%27-,build,-/my%2Dlanguages.so

**Comment by Akuli** [comment]
py-tree-sitter-builds includes the `.so` files.

**Comment by Akuli** [comment]
Actually, it includes one big `languages.so` which contains support for all languages. If you install it to a venv, the file is in `env/lib/python3.x/site-packages/tree_sitter_languages`.

**Comment by Moosems** [comment]
Then why are there only a few languages in https://github.com/Akuli/porcupine/tree/main/porcupine/plugins/highlight/tree-sitter-token-mappings?

**Comment by Akuli** [comment]
Those are what Porcupine supports. The full list for py-tree-sitter-languages (part of py-tree-sitter-builds) is here: https://github.com/grantjenks/py-tree-sitter-languages/blob/main/repos.txt

For other languages in the list, Porcupine doesn't use tree-sitter highlighting even though it's available in `languages.so`. Writing a good token mapping takes time, so there's only a few for popular languages.

**Comment by Moosems** [comment]
🤦. I done did a stupid. Isn't there a way to possibly automate their creation?

**Comment by Akuli** [comment]
I don't think it can be automated, but you might find a larger collection of mappings somewhere.

Note that "token mappings" is not an official name for these things. I made up the name. It's probably best to search for how to use tree-sitter to do syntax highlighting.

**Comment by Moosems** [comment]
Akuli there are mapping files in each repo. For example: https://github.com/tree-sitter/tree-sitter-javascript/blob/master/queries/highlights.scm

**Comment by rdbende** [comment]
Yes, but they need to be mapped to a syntax coloring tag in Porcupine

**Comment by Moosems** [comment]
There's just a few basic ones used in the `highlights.scm` files so conversion becomes a lot easier. Some basic documentation of the conversions would make the process easier in the future.
