### ISSUE TITLE
Long line marker is kinda buggy

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1296]
See https://github.com/DIP-Editor/DIP-dev/issues/63 for how I have the same issue in my own editor.

**Comment by Akuli** [comment]
That link points to an issue in a private repo, so I'll just repeat it here: When scrolling sideways on macos, the marker flashes instead of sliding side to side smoothly.

**Comment by Moosems** [comment]
https://github.com/Akuli/porcupine/assets/95927277/aeed6889-26d8-4f81-a6e3-41931bfa41ab


https://github.com/Akuli/porcupine/assets/95927277/e11e91b5-8df2-44da-b32a-944ee8be54b2

**Comment by Moosems** [comment]
> That link points to an issue in a private repo, so I'll just repeat it here: When scrolling sideways on macos, the marker flashes instead of sliding side to side smoothly.

Up and down too.

**Comment by rdbende** [comment]
```
Moosems: @rdbende Do you have any thoughts why the long line markers might be flickering?
rdbende: What GM do you use for it?
Moosems: GM?
rdbende: until i git grep for the code... :))
> GM?
rdbende: Geometry manager lol
Moosems: Place.
Moosems: :D.
rdbende: I don't think you should call place_forget
    Simply a place()
    And that will update it
Moosems: Well that… pretty much fixed it.
rdbende: really?
    wow
Moosems: Huh. That was easy.
```

**Comment by Akuli** [comment]
Porcupine already avoids unnecessary `place_forget()`. Please open a new issue if you aren't happy with how Porcupine behaves.
