### ISSUE TITLE
Can't `print` in tests

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1317]
Any idea why stdout (print) isn't being captured by pytest? I'm trying to use it to debug.

**Comment by benjamin-kirkbride** [comment]
I see, `--capture=no` is in `addopts` in `pytest.ini`.

Why is that?

**Comment by Akuli** [comment]
I prefer Python's normal way to show prints, in real time as they appear. This is especially useful when I set a breakpoint and then click something in the UI that triggers a print. I want to see it right then and there, not after pytest has finished running the test.

If you are used to pytest's way of showing prints, you can still specify `--capture=fd` or similar on the command line to override the pytest.ini setting.

**Comment by benjamin-kirkbride** [comment]
I see. I can see it helping in those instances, but it is pretty unexpected compared to how most projects use pytest. Not a big deal, but probably worth calling out in the dev docs.
