### ISSUE TITLE
File Dialog Unreadable

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1320]
By default the theme seems to make the font unreadable:
![image](https://github.com/Akuli/porcupine/assets/3373830/2f604ed3-28dd-4bfb-b247-80a7c71c275d)

Interestingly once items have been selected, it seems to change the font color?

Selected the first 3 individually:
![image](https://github.com/Akuli/porcupine/assets/3373830/13f52cd3-8771-408d-988e-65f9d061dd44)

**Comment by rdbende** [comment]
Porcupine uses another theme of mine, but this is related to
https://github.com/rdbende/Azure-ttk-theme/issues/35
and
https://github.com/rdbende/Azure-ttk-theme/issues/53

this is extremely annoying, but so far I was unable to fix this issue.

**Comment by rdbende** [comment]
It happens with all dark ttk themes.

**Comment by Moosems** [comment]
> It happens with all dark ttk themes.

.... So light mode is better XDDD?

**Comment by Akuli** [comment]
Duplicate of #1362
