### ISSUE TITLE
How to Handle Filetypes with Conflicting Extensions - Filetype Flavors

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1322]
This is kind of a broad issue that plagues all text editors/IDE's in my experience.

There are different "types" or "flavors" of files that overload file extensions. There are multiple examples and specifics of this. The problem for Porcupine (and all editors) is as such:
- Autodetection of "file type" based on the extension can be "wrong"
- Extensions that apply to certain "flavors" don't have a great way of knowing that.

# Examples
## SQL
A strong example of this would be SQL. There are many "flavors" of SQL, and SQL is further broken down by DDL, DML, DQL, etc etc . Some DBMS systems also support other syntaxes than SQL to be used in "SQL" files, for instance Postgres' `psql` tool [supports syntax much beyond SQL](https://www.postgresql.org/docs/current/app-psql.html#:~:text=psql%20provides%20a%20number%20of%20meta%2Dcommands%20and%20various%20shell%2Dlike%20features%20to%20facilitate%20writing%20scripts%20and%20automating%20a%20wide%20variety%20of%20tasks.)

This is a problem because how you might want to syntax highlight, lint, or autoformat one flavor would be different from another.

## Shell
another example might be shell. There are many shells, and they often use `.sh`.

This is somewhat less problematic because of the shebang, and perhaps porcupine could support using the shebang to determine shell flavors?

## Python
This example might be somewhat contrived, but different versions of Python obviously have different supported syntax. This is not specific to Python either.

## HTML
Many `.html` files are actually template files, like jinja, mustache, etc.

## Configuration Files
Many, many tools use `.yaml` for their programming/configuration, when in reality they are actually very specific DSL's. This problem likely also applies to things like `TOML`, `JSON`, and `INI`, `.txt`. Examples:
- Ansible (playbooks)
- Docker (compose)
- Kubernetes
- Terraform
- Grafana
- Python (pyproject.toml), `requirements.txt`

There are many more examples ommited. Now some of these you might be able to detect by evaluating the entire filename, like `docker-compose.yaml` should be pretty well trusted to be what it seems, but this is likely not universally true. Take `requirements.txt` for instance. Many projects (including this one) have the [Requirements File Format](https://pip.pypa.io/en/stable/reference/requirements-file-format/) with a name other than `requirements.txt`.

There are tools to highlight, lint, autoformat, etc each of the specific subtypes, but if we have 10 plugins to highlight 10 "flavors" of `.yaml`, we obviously don't want them to all have to fight eachother to figure out which one is "up next".

# Solutions
I don't have a fleshed out answer. Here are my thoughts:
- We should see how other editors handle this. I will say that VSCode specifically doesn't (to my knowledge) have a great answer to this. Basically extensions can register arbitrary new filetypes, but they don't seem to have a way to automatically detect the new filetypes in a good way, so often the user has to specify the "flavor" of filetype manually. Also, extensions tend not to call the new custom "flavors" the same thing, so I might have a "HTML Jinja" and a "Jinja (HTML)" and two extensions that only work with one of the aforementioned new custom types, such that I can't use them both at the same time on the same file.
- Some detection that goes beyond file extensions is likely needed (parse the HTML to see if it has Jinja in it, for instance). This obviously could have performance implications, but could be cached.
- Some state is likely required on a per-project (is this even a concept in Porcupine?) basis. If I manually state that a given file is "Python Requirements File Format", I want that to be remembered even if I close and reopen the tab. Even if the file is moved and/or changed (not sure how feasible this is).

**Comment by Akuli** [comment]
> Some state is likely required on a per-project (is this even a concept in Porcupine?) 

I avoid it, because I don't like how people accidentally commit things like `.vscode/` or `.idea/` to Git, and there's no way everyone will remember to add `.porcupine/` to their gitignores.

I think currently the only project-specific setting is which Python virtualenv is used, and those are stored in Porcupine's global settings as a dict with project paths as keys and venv paths as values. We could use the same approach for files in the somewhat rare cases where autodetecting isn't reasonable.

**Comment by benjamin-kirkbride** [comment]
> how people accidentally commit things like .vscode/ or .idea/ to Git

So this is actually what you are supposed to do. This permits devs to pull the repo and have their IDE be automagically configured for the project at hand. I agree that it is annoying clutter especially if it's for an IDE that you don't use, but [there is some ongoing discussion about how to address that](https://news.ycombinator.com/item?id=36472613).

Point being, I actually would be in favor of a `.porcupine/`. It is a very common pattern for a reason :)

**Comment by benjamin-kirkbride** [comment]
Why do we use EditorConfig if we don't want to have config state stored with projects?

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

**Comment by Akuli** [comment]
In most projects where Porcupine is used, there is only one person who uses Porcupine, so I think `.porcupine/` doesn't make sense as much as `.vscode/` does.

**Comment by benjamin-kirkbride** [comment]
But there is also the matter of different projects used by one porcupine user. If I want a different config for project 1 than project 2.

I don't think this is a huge deal atm, but I do think it's something in time we will find we want.

**Comment by Akuli** [comment]
As far as I can tell, there's nothing actionable here. Porcupine's solution is to not rely on the filetype very much, and instead apply things based on whatever other thing makes more sense, e.g. `.editorconfig` is applied based on the file extension. If someone thinks of a **concrete** solution to a **prefix** problem, just make a new issue.
