### ISSUE TITLE
README: pip upgrade fails

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1339]
Running `python3 -m pip install --user --upgrade pip` fails on a fresh install of Debian 12:

![eXcaW3Q](https://github.com/Akuli/porcupine/assets/18505570/169230fd-cd9c-4c6f-bee3-0b10677f6c3b)

I think we should just delete the command from the README. If someone has an ancient pip, they get an error that  they can google-search or post to Porcupine's issue tracker.

**Comment by benjamin-kirkbride** [comment]
I think we should encourage people to use `pipx` in general, unless they are developing, in which case they should be using a venv.
