### ISSUE TITLE
Actions - Initial Implementation

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1341]
Subtask of https://github.com/Akuli/porcupine/issues/1342

Reqs from https://github.com/Akuli/porcupine/issues/1335#issuecomment-1624329063

Requirements:
- [x] `actions.py`: the action classes, the registry and the related functions
- [x] A few producers (i.e. add an action in a few plugins)
- [x] One consumer

**Comment by Akuli** [comment]
Here is the old `actions.py` that I deleted and merged with menubar a few years ago: https://github.com/Akuli/porcupine/blob/3970a8ad898108f4979f2b004bf4be0d32b2e280/porcupine/actions.py

Not sure how useful that will be. It's not very nice, but it does a similar thing to we're planning and could be better than nothing as a starting point. Or maybe it is easier to start from scratch, I don't know :)

**Comment by benjamin-kirkbride** [comment]
@Akuli with [db47f32](https://github.com/Akuli/porcupine/pull/1349/commits/db47f32ecf278a034a7a942d6ede8f6a534af762) this is technically done (pending review ofc), by the requirements that were set out.

From here we could:
- finish the menubar implementation (https://github.com/Akuli/porcupine/issues/1343)
- work on a different consumer (probably the command palette)
- something else?

Thoughts?

**Comment by Akuli** [comment]
We basically need more producers (most plugins) and more consumers (key bindings, menubar, command palette). Once `actions.py` is in place, I think these don't really depend on each other and we can work on whatever we find interesting :)
