### ISSUE TITLE
Comment/uncomment current line without selecting

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/porcupine#1350]
Currently, I have to highlight at least one character on a row in order to use the function _Comment/uncomment selected lines_. I think this behavior is fine if I want to comment/uncomment several lines at once. 

**Desired behavior:**
If I want to comment out only one line, I should be able to do that simply by having the cursor set to that specific line.

**Comment by Akuli** [comment]
The challenge is figuring out which key binding to use for this. Something that is not used for anything else and ideally makes sense somehow. With text selected, it is whatever key produces the comment character of the language (so `#` in Python and `%` in LaTeX, for example).

Also, it is already possible to configure Porcupine to do this by adding this to your `keybindings.tcl` (menubar at top --> Settings --> Config Files):

```tcl
bind Text <Control-k> {
    %W mark set old_cursor_pos insert
    %W tag remove sel 1.0 end
    %W tag add sel {insert linestart} {insert linestart + 1 line}
    event generate . "<<Menubar:Edit/Comment//uncomment selected lines>>"
    %W tag remove sel 1.0 end
    %W mark set insert old_cursor_pos
}
```

The way this works is a bit of a hack. It selects the current line, invokes the button in menubar (only works when something is selected), and then restores the selection and cursor position. Ideally you wouldn't need to do this as a user :)

**Comment by rdbende** [comment]
I should mention, that there was #992 too, that didn't have this issue, tho @Akuli wasn't a fan of the idea.

**Comment by Akuli** [comment]
We can change the default behavior if I'm really the unusual one here :)

**Comment by ThePhilgrim** [comment]
I have to say I think what @rdbende says in #992 makes a lot of sense. I often comment out one single line, and having to select stuff before doing it feels really clumsy. 

Also, having `#` as a keybinding for this is slightly weird. Some people might not write Python, and therefore might be used to other ways to comment out. For example, if I'm a web developer using HTML/CSS/JS, I'm might not be familiar with #. Then the keybinding would have to change depending on what file is open. Which is super weird – in an html file, would then `<`, `!`, or `-` be the correct binding?

I believe the long-term goal of Porcupine would be to fit all programming languages. Therefore I would vote for a new keybinding. Most keybindings are to some extent arbitrary anyways.

**Comment by rdbende** [comment]
Also, typing a `#` on a Hungarian keyboard is kinda inconvenient. Probably only affects me though :D

**Comment by Akuli** [comment]
I talked about this with ThePhilgrim yesterday. The plan is:
- ThePhilgrim will make a PR that keeps the old behavior, but also adds a new keybinding that always works, regardless of filetype and whether something is selected or not.
- Once the PR is merged, I will try using the new key binding for a few weeks/months and decide if I want to keep the old one.
- Maybe (quite likely tbh) delete the old key binding logic that @Moosems still does not understand.
- If, after the deletion, I still want to continue using the old key binding, I will script it in `keybindings.tcl` (or whatever equivalent thing we will have at that time, if key binding stuff gets rewritten).
