### ISSUE TITLE
Default keybinding for comment/uncomment selected lines

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/porcupine#1352]
I think this function is used so often that it deserves a default keybinding.

I think the VS Code default (on Mac) is Cmd + Shift + 7 (probably Ctrl + Shift + 7).

**Comment by Akuli** [comment]
Type `#` if you're in a Python file

**Comment by Moosems** [comment]
On VS Code for Mac it's actually Command /

**Comment by Moosems** [comment]
> Type `#` if you're in a Python file

Commenting a lot of lines? That gets tedious fast.

**Comment by Akuli** [comment]
Porcupine will comment each line individually, if you have many lines selected in a Python file and you type `#`.

**Comment by Moosems** [comment]
Only python 🙁?

**Comment by Akuli** [comment]
Also works for other languages that have a single-character comment prefix, e.g. latex uses `%` comments similarly to Python's `#` comments, and typing `%` comments in latex. See also #1350.
