### ISSUE TITLE
Anchor plugin bug jumping from top to bottom & vice versa

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/porcupine#1353]
**To Reproduce:**

1. Go to Porcupine settings and enable "Jumping to previous/next anchor cycles to end/start of file".

2. Open a file, e.g. `foo.py`.

3. Make sure the file has two rows.
 
4. Set an anchor point on row 1 & one anchor point on row 2.

5. Set cursor on row 1. Remove the anchor point on row 1.

6. Use keyboard shortcut to jump to **next** anchor (down). **This works**.

7. Recreate anchor point on row 1. Make sure cursor is on row 1, then remove anchor point on row 1.

8. Use keyboard shortcut to jump to **previous** anchor (up). **The cursor does not move**.

**Comment by Akuli** [comment]
Does this setting help?

![s](https://github.com/Akuli/porcupine/assets/18505570/467b6601-08f3-415f-828b-dbb5edb07b5c)

**Comment by ThePhilgrim** [comment]
> Does this setting help?
> 
> ![s](https://user-images.githubusercontent.com/18505570/251818117-467b6601-08f3-415f-828b-dbb5edb07b5c.png)

See point 1 – the setting is activated when reproducing the bug.

**Comment by Moosems** [comment]
Im still unsure how anchor points work.

**Comment by rdbende** [comment]
When you press <kbd>Alt+a</kbd> it sets a mark (anchor) on the current line. You can press <kbd>Alt+Shift+⬆️</kbd> to see the line where the previos such mark was, or press <kbd>Alt+Shift+⬇️</kbd> to see the line with the next mark. Basically you set bookmarks in your file.

Another useful feature of the anchors plugin is that <kbd>Alt+e</kbd> adds an anchor to every line where the langserver plugin shows an error or a warning. Thus you don't have to scroll through the whole file to see the errors and fix them, you can just jump right to the problematic lines.

The plugin itself is not magic, it simply makes use of the `mark` feature of the text widget.

**Comment by ThePhilgrim** [comment]
@rdbende Excuse me, but I wrote this plugin. I would call it quite magical! xD

**Comment by Moosems** [comment]
*@ThePhilgrim took that personally, he will remember this.*

+5 points to anyone who gets the joke.

**Comment by Akuli** [comment]
If I add a *third* line and set an anchor point on it, this works. The bug only happens when the entire file contains just one anchor point.
