### ISSUE TITLE
"Unknown" Filetype

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1364]
My understanding is currently in Porcupine everything is a Python file unless proven otherwise. This is not great and is making troubleshooting https://github.com/Akuli/porcupine/issues/1363 difficult, and complicates https://github.com/Akuli/porcupine/issues/1357 broadly.

I propose that we have an explicit "Unknown" (or some other name) filetype to act as a semaphore.

**Comment by Moosems** [comment]
I'd just assume everything is a plain text file 🤷‍♂️. I am interested in the possibilities this may bring. What applications does it provide?

**Comment by benjamin-kirkbride** [comment]
It's less about any new features, and more about not having the "sort imports with isort" button be available for `.ini` files, and not having to have all the tests bend over backwards to accommodate new empty `FileTab`'s being "Python" by default.

**Comment by Moosems** [comment]
Python is the most often used file for those using Porcupine so I can understand how it became the default but an unknown file type would probably work better. Start with nothing and take the context clues to find the true file type.

**Comment by benjamin-kirkbride** [comment]
Right, exactly. I don't doubt it made sense at the time it was done :)

**Comment by Moosems** [comment]
Actually, would you be interested in taking a look at my own text editor? I originally had the same system of assuming Python once 🤣.

**Comment by benjamin-kirkbride** [comment]
Sure where is it?

**Comment by Moosems** [comment]
Let me add you as a collaborator. It's currently in alpha development so it's only open to close friends :). Welcome to the club my friend.

**Comment by Akuli** [comment]
You can already change Porcupine's default filetype in the settings dialog. Once that is set to something else than Python, there's no more Python defaulting.

With that, I don't think we need to add anything?

**Comment by benjamin-kirkbride** [comment]
I'm suggesting we should make this the default for Porcupine.

But also, is there a "Unknown" or "Plain Text" detector logic that exists? Not exactly sure what the logic path is there.

**Comment by Moosems** [comment]
If Python is the default, a new file extension say .xt will be highlighted as a Python file but if Unknown is the default it should act like plain text.

**Comment by Akuli** [comment]
> Not exactly sure what the logic path is there.

The logic is defined `guess_filetype()` and `get_filetype_for_tab()` in `plugins/filetypes.py`. It works like this:
1. If the tab has never been saved, it does not have a file name and we really don't have much to go off of. We use the default filetype from the settings dialog (usually Python).
2. If the filename matches one of the patterns (e.g. ?*.py`) in filetypes.toml or default_filetypes.toml, use that filetype.
3. If the file exists, and its content starts with a shebang (e.g. `#!/usr/bin/env python3`) that matches a shebang regex (e.g. `'python(\d(\.\d)?)?$'`) in filetypes.toml or default_filetypes.toml, use that filetype.
4. Ask the Pygments syntax highlighting library if it can guess the file type. If it can, create a new "dummy filetype" on the spot that does syntax highlighting correctly, but otherwise don't apply any filetype-specific settings (e.g. no langserver).
5. If all else fails, use `"Plain Text"`.

> But also, is there a "Unknown" or "Plain Text" detector logic that exists? 

Kind of. Steps 4 and 5 do what I think the proposed "Unknown" filetype is supposed to achieve, but I'm not sure.

> a new file extension say .xt will be highlighted as a Python file

Why?

**Comment by benjamin-kirkbride** [comment]
I think one of us is confused.

My understanding is that when a new `FileTab` is made, it defaults to being of the type "Python". This complicates tests, is honestly mostly why it bothers me.

I am wanting a new `FileTab` to not default to Python, but default to some default that is "Unknown", "Plain Text", `None`, or something else equivalent.

**Comment by Akuli** [comment]
If it is a testing problem, there are a few things you can try:
- Set the filetype at the start of the test:
    ```python
    from porcupine.plugins.filetypes import filetypes, apply_filetype_tab

    def test_foo(filetab):
        apply_filetype_to_tab(filetypes["Plain Text"], filetab)
        ...tdd go brrr ...
    ```
- Create a fixture that sets the filetype to plain text. You probably already know how fixtures work :)
- Change the default filetype in `global_settings`. Affects new tabs only, existing tabs (such as the `filetab` fixture) are unaffected.

**Comment by benjamin-kirkbride** [comment]
> Change the default filetype in global_settings. Affects new tabs only, existing tabs (such as the filetab fixture) are unaffected.

Are you saying do this to Porcupine (like in a PR), or do this on a test-by-test basis? My desire here is to do the former.

**Comment by Akuli** [comment]
I suggested doing it on a test-by-test basis. I still don't see why you don't want users to get a Python file by default, if they program mostly in Python. In fact, this used to be how it worked, but I got complaints about "syntax highlighting not working".

**Comment by benjamin-kirkbride** [comment]
I guess it's a philosophical thing. Is Porcupine a Python editor that happens to support other things, or is it a text editor that happens to be mostly used (and has best support) for Python. The way the README is written implies the latter, IMO

**Comment by benjamin-kirkbride** [comment]
> this used to be how it worked, but I got complaints about "syntax highlighting not working".

The solution for this is filetype autodetection, no? What if someone complains that when they open a new tab and start writing JS it doesn't highlight right?

**Comment by Akuli** [comment]
If auto-detection is improved so much that it does the right thing as you start typing, then we can get rid of the default filetype setting. Until then it is needed.

IMO this is not so much about Porcupine being primarily a Python editor, because you can set the default filetype to something else than Python if you don't program in Python much.

**Comment by benjamin-kirkbride** [comment]
I'll throw out there that other editors (IME) behave the way you initially described as being the "problem": if you open a new blank editor tab you get no highlighting or extensions (other than ones that opt into working with "blank"/"default" file types)

> IMO this is not so much about Porcupine being primarily a Python editor, because you can set the default filetype to something else than Python if you don't program in Python much.

Defaults (as in how things come configured/out of the box) matter

---

This isn't a hill I want to die on, as it's not actually hurting anything, so I'll drop it  (for now :wink:)

**Comment by Moosems** [comment]
I thought Porcupine was a code editor (not the same as a text editor) that heavily supports and focused on Python.
