### ISSUE TITLE
Debian 12: default font has warning triangle

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1368]
In a Debian 12 VM, with whatever the default desktop is, if I open the settings, the font family chooser has a warning triangle next to it before I even touch it. I might take a screenshot later.

Once I set the font from "Noto Sans Mono" (default) to something else, the triangle goes away. Editor works even with the triangle though.

**Comment by Moosems** [comment]
Does hovering over the triangle gleam any info?

**Comment by Akuli** [comment]
No, I have not added a tooltip to it. If I remember correctly, the triangle is supposed to show up when you type a font name that doesn't exist.
