### ISSUE TITLE
Fedora 38: `settings._is_monospace` segfaults

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#1370]
@Akuli I know you had a ticket on the Tk core about this, but this seems to happen with a bunch of other font families as well.
I had to manually edit `~/.cache/porcupine/font_cache.json` to be able to launch Porcupine.

**Comment by Akuli** [comment]
Can you add a print, so that we see the name of the problematic font (if you don't know it yet)? We already skip anything with "emoji" in the name, I think.

**Comment by rdbende** [comment]
```
Source Code Pro
Standard Symbols PS
Symbola
URW Bookman
URW Gothic
Wazirmatn
```

These seem to be pretty random (monospace, emoji and plain serif), except that they are adjacent items at the very end of the alphabetical list.

**Comment by rdbende** [comment]
Running it on just a slice of `font.families()` produces the same results.

**Comment by Akuli** [comment]
So if you add an `if` statement that skips those fonts, then it doesn't crash? What is the font just before `Source Code Pro` in the alphabetical list?

**Comment by rdbende** [comment]
> So if you add an if statement that skips those fonts, then it doesn't crash?

Yup
> What is the font just before Source Code Pro in the alphabetical list?

`STIX`

**Comment by Akuli** [comment]
What happens if you skip STIX but don't skip the others? Does it still crash as soon as it gets to Source Code Pro?

**Comment by rdbende** [comment]
After running `fc-cache -fv` I can't repro.

**Comment by Moosems** [comment]
Does Fira Code break?

**Comment by rdbende** [comment]
I don't have that font, and I can't reproduce this anymore.

**Comment by Moosems** [comment]
I'd highly recommend the font, it's DIP'a new default actually. Super pretty and monospaced.

**Comment by Akuli** [comment]
Nothing actionable. Let's make a new issue if someone runs into this again.
