### ISSUE TITLE
Alt+S / Sort Lines: selects a bit too much

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1375]
(Now there are 200 open issues, yay)

At work we have text files that look like this:

```
[foo]
    akuli
    dingdingding
    banana
    catris
```

When I press Alt+S in the middle of this, it becomes:

```
    akuli
    banana
    catris
    dingdingding
[foo]
```

because `[` comes after space in ASCII. This isn't great.

It would be better to only sort the lines that have the same indentation level as the current line, so this would instead become:

```
[foo]
    akuli
    banana
    catris
    dingdingding
```

**Comment by rdbende** [comment]
> (Now there are 200 open issues, yay)

I knew you were going to open one more, just because of that LOL

**Comment by Moosems** [comment]
I hope DIP never gets over 50 XD.
