### ISSUE TITLE
Merging requirements.txt and requirements-dev.txt

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1381]
Dependencies are specified in 3 places:
- `requirements.txt` (used when setting up dev environment)
- `requirements-dev.txt` (used when setting up dev environment)
- `pyproject.toml` (used by pip)

There is also a test that fails if `requirements.txt` and `requirements-dev.txt` don't match.

I think we should merge `requirements.txt` and `requirements-dev.txt` into a single file that installs everything you need for developing. The test would be changed to ensures that everything in `pyproject.toml` is in the new combined file, but not require the same in reverse, because dev-only dependencies would go in `requirements.txt` instead.

There is also a standard way to specify dev dependencies in `pyproject.toml`, so that you can do `pip install -e ".[dev]"` for instance. We could also use that.

**Comment by benjamin-kirkbride** [comment]
> There is also a standard way to specify dev dependencies in pyproject.toml, so that you can do pip install -e ".[dev]" for instance. We could also use that.

This would be my vote, as you know :)

**Comment by benjamin-kirkbride** [comment]
I am going to cook up a PR for this
