### ISSUE TITLE
git status plugin: ä character

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1385]
1. Open a project tracked with Git in porcupine.
2. Create a file with `ä` in file name. Commit it to Git.
3. Open the file in Porcupine.
4. Modify the file and save.

Expected result: file shows up as red in Porcupine's directory tree

Actual result: file shows up as white

**Comment by Moosems** [comment]
Red means new file? What does the color signify?

**Comment by Akuli** [comment]
Colors are same as with `git status`. Very standard stuff, every git user knows the meanings. But here they are in case it is somehow unclear how they work:

- white = no changes
- green = all saved changes added with `git add`, will be included in commit
- red = there are changes that have not been `git add`ed
- red = untracked

Because Git uses red for two things, Porcupine uses slightly different shades of red for the two.

**Comment by Moosems** [comment]
Do guy doesn't notice the file?

**Comment by rdbende** [comment]
It does notice them, but with some non-unicode encoding, or idk

```console
$ git init
Initialized empty Git repository in /tmp/foo/.git/

$ touch bigyó.txt bigyo.txt

$ git add *

$ git ls-files
bigyo.txt
"bigy\303\263.txt"

```

**Comment by Akuli** [comment]
Apparently you're supposed to interpret the `\303\263` in ``"bigy\303\263.txt"` as octal (base 8) numbers:

```
>>> 0o303
195
>>> 0o263
179
```

These numbers can then be interpreted as bytes, because they are in the range 0 - 255. That forms a valid UTF-8 string. The string contains only one character even though there are two bytes, because that's how UTF-8 works.

```
>>> bytes([195, 179]).decode("utf-8")
'ó'
```

I can already think of lots of corner cases where stuff might not work, and must be tested when this is implemented:
- space in file name
- quote in file name
- backslash in file name
- backslash followed by numbers in file name

**Comment by rdbende** [comment]
Ah, I see

**Comment by Akuli** [comment]
I think I should explain this, because it tends to come up when debugging stuff, and if you don't understand it, you will probably try to experiment with the thing until it works and you'll likely get very frustrated :D

For a programmer, a byte is a number from 0 to 255. Computers really like bytes. A file is really just a list of bytes with a name. Your computer's RAM is just a big fixed-size array of bytes.

An encoding is a way to convert text to bytes. It converts (encodes) a string to a sequence of bytes that you can have a string in the computer's memory, write a string to a file, send a string over network, or whatever it is you want to do with strings.

Here are some examples:
- ASCII is an encoding that assigns the numbers 0 - 127 to one character each and leaves 128 - 255 unused. This means that there are only 128 ASCII characters. Anything else is invalid ASCII.
    ```
    >>> list('a'.encode('ascii'))
    [97]
    >>> list('ÿ'.encode('ascii'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 0: ordinal not in range(128)
    ```
- Latin-1 is an encoding that extends ASCII by assigning the remaining numbers to more characters, so you get 256 supported characters. There's of course more than 256 characters, so there are still characters that don't work.
    ```
    >>> list('a'.encode('latin-1'))
    [97]
    >>> list('ÿ'.encode('latin-1'))
    [255]
    >>> list('π'.encode('latin-1'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'latin-1' codec can't encode character '\u03c0' in position 0: ordinal not in range(256)
    ```
- Utf-8 is the "standard" encoding that the world uses almost everywhere now. It works differently from the other two, and supports all Unicode characters. Basically, every character you will ever see on a computer screen.
    ```
    >>> list('a'.encode('utf-8'))
    [97]
    >>> list('ÿ'.encode('utf-8'))
    [195, 191]
    >>> list('π'.encode('utf-8'))
    [207, 128]
    ```
    Because UTF-8  can use multiple bytes, it can do more than 256 different characters. Basically, there is many more combinations you can make out of two bytes than one byte. It is still backwards-compatible with ASCII, so ASCII files continue to "just work" even though almost everything now wants UTF-8.

**Comment by Moosems** [comment]
And then there's utf-16....

**Comment by Akuli** [comment]
UTF-16 is basically the same thing for pairs of bytes.

When windows became a thing, microsoft decided to use 2-byte (16-bit) values for characters. There are 256 * 256 = 65536 combinations you can make out of two bytes. And you're never going to have more than 65536 different characters anyway, so it should work, right?

Wrong. We now have emojies etc.

UTF-16 solves this by sometimes using two 16-bit (2 byte) units for a character, just like UTF-8 sometimes uses two or more 8-bit (1 byte) units for a charater.

UTF-16 mostly reminds me of the mess that microsoft now has, because a long time ago they decided to go with 16 bits per character. I came across that when handling file names in a game written in C. You have two options: "ANSI", which depends on the language of the user's Windows installation and is kinda dumb, and "UNICODE" which actually means UTF-16 rather than unicode. So neither of the two options is UTF-8, and neither of them is unicode. This means you have to convert between UTF-8 and UTF-16 a lot.

**Comment by Moosems** [comment]
Interesting. And why don't emojis fit in that large character count?

**Comment by Moosems** [comment]
Also everyone is on the Discord right now ;).

**Comment by Akuli** [comment]
65536 is not large by modern standards. There are so many different Unicode characters now, 149186 [according to wikipedia](https://en.wikipedia.org/wiki/Unicode).

**Comment by Moosems** [comment]
So upgrade to 32 bit? As we increase computing power and memory size such an upgrade should become possible, no?

**Comment by Akuli** [comment]
Have fun convincing Microsoft to break all existing `.exe` files.

**Comment by Akuli** [comment]
Alternatively, to create a third version of *every function* that deals with strings. They already have two variants of all function, e.g. `GetModuleFileNameA()` and `GetModuleFileNameW()` to get the path to a currently running exe or dll.

**Comment by Moosems** [comment]
Is there an easy way to check the encoding of a file?

**Comment by Akuli** [comment]
No :)

There are libraries and programs that claim to do it, but they often guess wrong. For example, old versions of internet explorer used to do this. It caused weird problems where a one-character edit could throw off the auto-detection code, and suddenly you would see lots of chinese characters instead of whatever the intended language was. (There are encodings that mostly support chinese characters, similarly to how latin-1 is mostly european characters.)

But detecting doesn't really have anything to do with microsoft's encoding problem. It applies to *every* interaction that involves strings exchanged between the OS and an application.  So simply put, any changes to how it works would be painful.

Unix-like operating systems (linux, macos, ...) are simpler in this regard, they just treat everything as a sequence of bytes so you can put UTF-8 strings everywhere and be happy :)

**Comment by Moosems** [comment]
So how does detection work?

**Comment by Akuli** [comment]
You try a few different encodings and see which one produces the most reasonable results :)

Ideally all encodings would be like utf-8, where you get an error if the data isn't valid utf-8. For example, here's attempting to interpret latin-1 data as utf-8:

```
>>> "örkkimörkkiäinen".encode("latin-1").decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte
```

But with less fancy "1 byte = 1 character" encodings you tend to instead get the wrong characters. Here's what happens if your data is in utf-8 but you interpret it as latin-1:

```
>>> "örkkimörkkiäinen".encode("utf-8").decode("latin-1")
'Ã¶rkkimÃ¶rkkiÃ¤inen'
```

A good encoding detector would realize that latin-1 is probably not the right encoding here, because the result just looks like garbage in some sense.

So what exactly is defined to be garbage, I don't know. I haven't ever written an encoding detector. For example, Porcupine assumes UTF-8 (or whatever editorconfig sets), and asks the user if it doesn't work.

**Comment by Moosems** [comment]
I might go with that then :).
