### ISSUE TITLE
[Feature Request] `porc` entry point

### ISSUE THREAD

**Issue by Zaab1t** [Akuli/porcupine#14]
`porcupine` is too long to type

**Comment by Akuli** [comment]
I have `alias porcu=porcupine`. Can you do some googling about whether someone has already created an executable called `porcu`? Of course, it would be very unlikely to conflict anyway but just in case.

**Comment by Zaab1t** [comment]
I can't find anything for `porcu` nor `porc`!

**Comment by Akuli** [comment]
Now there's a `porcu` command instead of `porcupine`.
