### ISSUE TITLE
Restarting Porcupine Between Tests

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1405]
With the way the tests work right now, Porcupine is started once, and then all tests run consecutively in the Porcupine instance. This means that there will always be various ways to influence one test from another if you try.

"Restarting" Porcupine between the tests isn't really an option, if it means that `setup()` functions in all plugins would be called again. I imagine that would make testing a lot slower. It's not very easy to try it now, because there's currently no good way to restart Porcupine without launching a whole new Python process.

_Originally posted by @Akuli in https://github.com/Akuli/porcupine/issues/1402#issuecomment-1666932073_

---

> I imagine that would make testing a lot slower.

Is this the only reason that you thing that restarting Porcupine between tests isn't viable? I think that it's possible that using xdist, even with restarting Porcupine each time, things will be much faster.

**Comment by Akuli** [comment]
As I already mentioned, there's no good way to do this. A lot of things rely on global state. It would be possible to "clean" that up, but it wouldn't be easy, and not really worth it IMO: having multiple simultaneous `tkinter.Tk` instances (within the same process) is discouraged/surprising anyway.

This isn't really a blocker for xdist though. If xdist spawns two processes, there would be two Porcupine instances in those two processes.
