### ISSUE TITLE
where should sansio_lsp_client stop and the langserver plugin start?

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1407]
I have been on a bit of an LSP kick and found that our very own @Akuli appears to have write access to https://github.com/PurpleMyst/sansio-lsp-client

Spending some time looking through the `langserver.py` plugin, it seems like (not at all trying to be rude :sweat_smile:, just using the words used in the comments) a lot of it is hacky. I can't help but think that a lot of it probably should be done in the client library?

I'm just trying to get a gauge of what the thought is for the relationship and philosophy between these projects.

**Comment by rdbende** [comment]
They were developed at the same time, with each other in mind. The plugin is in the "Works, don't touch it" state, according to *Our Very Own @Akuli* (https://github.com/Akuli/porcupine/issues/1383#issue-1801435437). The langserver will probably require changes on both sides anyway, because Pyright is kinda weird, and currently doesn't work with sansio-lsp-client

**Comment by Akuli** [comment]
`sansio-lsp-client` is meant to be useful whenever you need a langserver. Not all uses of langservers are editors. For example, one user of `sansio-lsp-client` uses it to run clangd to do some static analysis on C code (or C++ code?).

**Comment by Akuli** [comment]
Now that I read this more carefully:

> looking through the langserver.py plugin, it seems like (...) a lot of it is hacky. 

Yes, and there is also lots of workarounds/hacks for stuff that should really be fixed in sansio-lsp-client :)

**Comment by benjamin-kirkbride** [comment]
> sansio-lsp-client is meant to be useful whenever you need a langserver. Not all uses of langservers are editors.

Yes, I am playing around with just such a thing right now, but I found trying to use `sansio-lsp-client` directly to not really be possible for me; no docs, and the tests (to me) don't have enough examples to figure out how to use it. So I ended up copying the langserver plugin and hacking it apart to try to meet my needs, but that wasn't exactly easy nor fun either :sweat: 

> Yes, and there is also lots of workarounds/hacks for stuff that should really be fixed in sansio-lsp-client :)
I'm thinking things like `NonBlockingIO`, and maybe even `LangServer` (obviously in a more agnostic form, more focused on sending and receiving from a langserver). Curious what your thoughts are on how it could be improved?

**Comment by Akuli** [comment]
>  no docs, and the tests (to me) don't have enough examples to figure out how to use it. 

I agree that the docs situation isn't ideal.

I'm actually pretty happy with how sansio-lsp-client tests work in principle, and I think they are a great way to get familiar with how it works. They show you how to:
1. do your own IO and connect it with sansio-lsp-client
2. download and run a langserver
3. tell the langserver about the existence of a file
4. ask for autocompletions in the given file.

That said, even though the test code is easy to understand in principle, it just looks messy and confusing.

>> Yes, and there is also lots of workarounds/hacks for stuff that should really be fixed in sansio-lsp-client :)

> I'm thinking things like `NonBlockingIO`

Look, it has `sansio` in the name. It literally means it doesn't do IO. You as a user of the library do the IO. This way sansio-lsp-client assumes *nothing* about how IO is done. You might need to use blocking IO, asyncio, tkinter, or some completely other custom thing that I have never heard of. No matter how you send and receive bytes with the langserver, you will be able to use sansio-lsp-client.

> and maybe even LangServer (obviously in a more agnostic form, more focused on sending and receiving from a langserver).

It already has the `Client` class. What other features of `LangServer` would you like to see included in sansio-lsp-client?

**Comment by benjamin-kirkbride** [comment]
> it has sansio in the name
Ah, I tried so hard to figure out what "sansio" meant, I assumed it was from another language or something :sweat_smile: 

---

Alright, maybe it's a skill issue then. I guess I will figure it out as time goes on if I keep up with what I'm working on.

**Comment by Akuli** [comment]
> Alright, maybe it's a skill issue then.

To me, more like a documentation issue. Ideally sansio-lsp-client's README or some other documentation would explain pretty much everything I have said about it here. I would be very confused if I knew nothing about sansio-lsp-client or Porcupine's langserver situation, and I tried to figure it all out by reading code :)
