### ISSUE TITLE
"Quit" is never clickable in file menu

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1422]
Introduced in #1349

**Comment by taahol** [comment]
https://stackoverflow.com/q/11828270/17635987

**Comment by taahol** [comment]
https://github.com/Akuli/porcupine/blob/d35e12e1163356fb1b2c9638efb8ed618690dcb5/porcupine/menubar.py#L298

Callback isn’t called when there is no tabs.

**Comment by Akuli** [comment]
IMO it should just pass a `None` to the callback when there are no tabs, so that the callback can decide what to do.
