### ISSUE TITLE
right-click menu placing

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1429]
![2023-12-06-134224_1920x1080_scrot](https://github.com/Akuli/porcupine/assets/18505570/deabf402-c48b-4958-b1a9-6a63fca242f8)

The right-click menu appears exactly where the mouse is. This makes it easy to accidentally click the first menu item. It would be better to place the menu e.g. 10px below the mouse.

Porcupine has several right-click menus, and they should be all fixed at once. They all use the `tk_popup()` menu, so to find all places that need to be changed, you can search for `tk_popup` in the project (with e.g. `git grep tk_popup`).

**Comment by Akuli** [comment]
Maybe it would be good to also offset 10px to the right, because menus can also appear like this:

![image](https://github.com/Akuli/porcupine/assets/18505570/297f5fbc-f0ff-4a90-90e1-280437916aae)

**Comment by ethical-haquer** [comment]
Noob question here, what is the proper way to create a pull request for an issue? I followed the directions for contributing, but once I have made changes on my branch, what is the proper way to create a pull-request for an issue? 😊 (Yes, it's my first time doing this)

**Comment by Akuli** [comment]
Nice to see you contributing :)

Put `Fixes #1429` to the description of the pull request. The `Fixes` is a magic keyword for GitHub that links the pull request together with an issue, so that the issue closes when the pull request is merged.
