### ISSUE TITLE
Delete `blockcursor` plugin?

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1499]
I'm pretty sure nobody uses it. I'll close this if I'm wrong.

**Comment by Moosems** [comment]
What does it do?

**Comment by rdbende** [comment]
It allows to toggle between the beam and the block cursor (block meaning that the insert cursor is as wide as a character).
The plugin was probably my first contribution to Porcupine, and it's pretty useless, as no one wants to edit text with a blockcursor.

That said, you'd probably get answers faster, if you just read the code.

**Comment by Moosems** [comment]
@rdbende I second the thanks :)
