### ISSUE TITLE
irc plugin

### ISSUE THREAD

**Issue by Zaab1t** [Akuli/porcupine#17]
does an irc plugin exist? Remember talks of it but can't find it.

**Comment by Akuli** [comment]
It was waiting for me to do something to it somewhere at some point. At some point I got interested in a bunch of other projects and kind of forgot it :(

**Comment by Akuli** [comment]
I'm feeling like I want to work on the IRC plugin this weekend :D

**Comment by Akuli** [comment]
I created [an irc branch](https://github.com/Akuli/porcupine/tree/irc) for this.
