### ISSUE TITLE
clangd 11

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#192]
This commit makes sansio-lsp-client work with clangd 11. But looking at the code, it seems return a different datatype in that case:

https://github.com/PurpleMyst/sansio-lsp-client/commit/79770bdc4d234a614cedd33dc8587f8405ffcba5

**Comment by PurpleMyst** [comment]
I *think* it should be uniform even in the `except` case, since I handle the `CompletionItem[]` case by turning it into a `CompletionList` like the spec defines:

> result: CompletionItem[] | CompletionList | null. If a CompletionItem[] is provided it is interpreted to be complete. So it is the same as { isIncomplete: false, items }

**Comment by Akuli** [comment]
I wonder if [this code](https://github.com/Akuli/porcupine/blob/440018f19409e99b22b70893f51f357611122f04/porcupine/plugins/langserver.py#L454-L457) is necessary.

**Comment by PurpleMyst** [comment]
As far as I can tell, it isn't

**Comment by Akuli** [comment]
>makes sansio-lsp-client work with clangd 11

This turned out to be false. I created https://github.com/PurpleMyst/sansio-lsp-client/issues/34
