### ISSUE TITLE
porcupine does not start up on Windows 10

### ISSUE THREAD

**Issue by PurpleMyst** [Akuli/porcupine#22]
With scoop-installed python 3.7.0, running `python3 -m porcupine` gives this traceback
```python
C:\Users\me\Downloads\porcupine>python3 -m porcupine                                                                Traceback (most recent call last):                                                                                        
File "C:\Users\me\scoop\apps\python\current\lib\runpy.py", line 193, in _run_module_as_main                           
"__main__", mod_spec)                                                                                                 
File "C:\Users\me\scoop\apps\python\current\lib\runpy.py", line 85, in _run_code                                      
exec(code, run_globals)                                                                                               
File "C:\Users\me\Downloads\porcupine\porcupine\__main__.py", line 147, in <module>                                   
main()                                                                                                                
File "C:\Users\me\Downloads\porcupine\porcupine\__main__.py", line 126, in main                                       
porcupine.init(verbose_logging=args.verbose)                                                                          
File "C:\Users\me\Downloads\porcupine\porcupine\_run.py", line 36, in init                                            
_logs.setup(verbose_logging)     
File "C:\Users\me\Downloads\porcupine\porcupine\_logs.py", line 64, in setup                                          
file_handler = logging.FileHandler(logfile, 'x')                                                                      
File "C:\Users\me\scoop\apps\python\current\lib\logging\__init__.py", line 1041, in __init__                          
StreamHandler.__init__(self, self._open())                                                                            
File "C:\Users\me\scoop\apps\python\current\lib\logging\__init__.py", line 1070, in _open                             
return open(self.baseFilename, self.mode, encoding=self.encoding)                                                   
OSError: [Errno 22] Invalid argument: 'C:\\Users\\me\\AppData\\Local\\Akuli\\Porcupine\\Cache\\logs\\2018-08-05T22:04:21.txt'  
```

**Comment by Zaab1t** [comment]
The file mode on the `logging.Filehandler` is set to `x`: https://github.com/Akuli/porcupine/blob/master/porcupine/_logs.py#L64

This means "open for exclusive creation, failing if the file already exists": https://docs.python.org/3/library/functions.html#open

So I'm guessing the file already exists. Is this possible?

**Comment by Akuli** [comment]
@PurpleMyst , can you check which files you have in the porcupine appdata folder? `cd C:\Users\me\AppData\Local\Akuli` followed by `tree /f`

**Comment by Akuli** [comment]
@PurpleMyst try this in python's `>>>` prompt. If it fails with a similar error, your python is broken and this is not porcupine's fault.

```
>>> open('this file does not exist.txt', 'x')
```

**Comment by Akuli** [comment]
which bitness of windows 10? how exactly did you install the python, and what does "scoop-installed" mean?

**Comment by Akuli** [comment]
nevermind i can reproduce this

**Comment by Akuli** [comment]
this is weird. If a filename contains two colons in a funny way, it's invalid. For example, `aa::.txt` is not a valid file name on windows 10, even though `aa:.txt` is. I think file names that contain two semicolons in some specific way are special in some way on windows.

I replaced `:` with `-`. Should be fixed now.

**Comment by Akuli** [comment]
irc message from PurpleMyst:

```
<__Myst__> Akuli: works now
```

**Comment by PurpleMyst** [comment]
[The Windows documentation](https://docs.microsoft.com/it-it/windows/desktop/FileIO/naming-a-file#file_and_directory_names) states that there are many characters you can't put in a filename. Might want to do a quick check over Porcupine that none of those characters are used.
