### ISSUE TITLE
DPI awareness

### ISSUE THREAD

**Issue by Tetralux** [Akuli/porcupine#24]

**Comment by Akuli** [comment]
I figured out a way to make Porcupine somewhat DPI-aware when I needed to use it on Windows last summer. I did something with SetProcessDpiAwareness, but that's all I remember. I'll add this to Porcupine when I feel like it or someone wants me to add it.

**Comment by Akuli** [comment]
@Tetralux Seems like it's been exactly one year since you requested this, and I'm finally working on it. Can you try running a small python program on windows 10? My windows 10 virtual machine is so terribly slow that I don't want to use it.

**Comment by Akuli** [comment]
To make progress with this, I need someone with a sanely working new Windows system to run this:

```python3
import ctypes, tkinter

ctypes.windll.shcore.SetProcessDpiAwareness(1)

root = tkinter.Tk()

root['menu'] = mainmenu = tkinter.Menu(root)
submenu = tkinter.Menu(mainmenu, tearoff=False)
mainmenu.add_cascade(label='Foo', menu=submenu)
for i in range(10):
    submenu.add_command(label='Blah ' + str(i))

t = tkinter.Text(root)
t.insert('1.0', 'Bla bla bla\n'*10)
t.pack()
root.mainloop()
```

Does it work? Does it work better if the `1` of `SetProcessDpiAwareness(1)` is replaced with `0` or `2`?

**Comment by PurpleMyst** [comment]
This is what it looks like, both with 0 and 1. I also tested 2 but forgot to include it in the screenshot.
![screenshot of situation](https://user-images.githubusercontent.com/29232169/104807860-6560cc00-57e2-11eb-8b6c-bd10b9017ac8.png)
It looks the same on all settings to me. Maybe my setup is wrong?

**Comment by Akuli** [comment]
I think it only makes a difference when your screen resolution is smaller than the biggest possible, i.e. one pixel of application corresponds to multiple pixels on screen.

**Comment by Akuli** [comment]
We could copy what IDLE does and call this done: https://bugs.python.org/issue33656
