### ISSUE TITLE
Proxy Error encountered

### ISSUE THREAD

**Issue by Esme76** [Akuli/porcupine#25]
When trying to install Porcupine with the following command in PowerShell: py -m pip install --user https://github.com/Akuli/porcupine/archive/master.zip, I am getting the following error:

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 authenticationrequired'))': /Akuli/porcupine/archive/master.zip
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /Akuli/porcupine/archive/master.zip (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 authenticationrequired')))

Thoughts on how to resolve this?

**Comment by PurpleMyst** [comment]
Does this issue happen only when trying to install porcupine or even with other packages?

**Comment by Akuli** [comment]
You can try downloading https://github.com/Akuli/porcupine/archive/master.zip with a web browser, and then something like this on powershell:

```
py -m pip install --user "C:\path\to\your\download\folder\porcupine-master.zip"
```

**Comment by Esme76** [comment]
Akuli - I tried your steps, and I am still getting an error. This time a bit different than the first time:

  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 authenticationrequired'))': /simple/appdirs/
  Could not find a version that satisfies the requirement appdirs (from Porcupine==0.70.0) (from versions: )

**Comment by Akuli** [comment]
You seem to be using a proxy. I found some instructions for using a proxy with pip:
- https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server
- https://stackoverflow.com/a/43473312

I have never used a proxy myself, so I might not know how to help if you have trouble following those links. Let me know anyway.

**Comment by Akuli** [comment]
Feel free to reopen this issue if you are still interested in this
