### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by Shurlyn** [Akuli/porcupine#26]
When I write things the code does not change color

**Comment by Akuli** [comment]
You need to save the file first to tell Porcupine how you want the file colored (e.g. `something.py` for Python syntax highlighting), or you can choose the filetype from the menu.

If this doesn't help, can you take a screenshot showing the whole porcupine window?

**Comment by Akuli** [comment]
It works for me on windows and linux. Reopen the issue if it still doesn't work for you with the latest porcupine.

**Comment by Akuli** [comment]
if you don't want to bother with saving the file to `something.py`, go to *Edit* --> *Porcupine Settings* --> *Default filetype for new files*
