### ISSUE TITLE
type hints and mypy

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#28]
checklist that tracks status of `mypy-pathlib` branch:

- [x] add type hints to code until `mypy` check with `--strict` passes
- [x] replace mysterious dictionaries with dataclasses
- [x] update readme and api docs and stuff to use type hints
- [x] make sphinx work with type hints

**Comment by Akuli** [comment]
`porcupine.settings` and a few other things will be tricky

**Comment by PurpleMyst** [comment]
Here's a python library, [pydantic](https://pydantic-docs.helpmanual.io/), that is made exactly for "Data validation and settings management using python type annotations"

**Comment by Akuli** [comment]
I think I'll go with dataclasses from stdlib, there's a backport for 3.6 on pypi.

I was going to use `attrs` but `sansio-lsp-client` requires a specific version of `attrs`, and things would break if porcupine or sansio-lsp-client (but not both) decides to update their `attrs`.

**Comment by PurpleMyst** [comment]
What do you mean by `sansio-lsp-client` requires a specific version? It supports any `18.X.X`, although the latest is `19.X.X`.. We could update

**Comment by Akuli** [comment]
We could update, but porcupine and `sansio-lsp-client` must be using the same version because you can have only one `attrs` installed at a time in a virtualenv or other python.

**Comment by PurpleMyst** [comment]
Last attrs update was 9 months ago, we could lock both attrs and sansio-lsp-client to the same version

**Comment by Akuli** [comment]
currently I'm creating and submitting tkinter pull requests to typeshed to make mypy usable with tkinter. Porcupine also has a `my_stubs` directory now but my goal is to pull request all of it to typeshed.

**Comment by Akuli** [comment]
will work on documentation once I don't need to use `my_stubs` anymore, I don't really want to explain in the documentation what those are

**Comment by Akuli** [comment]
all done, still uses `my_stubs` but readme explains how they work
