### ISSUE TITLE
highlight plugin rehighlights entire file every time a single character changes

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#39]
To fix this, I can't just start highlighting from the part of the file visible at the very top of the editor window, because a multi-line Python `"""` string or a C `/*` comment could begin before the top of the view and end after the top of the view. In cases like this, it's necessary to look at what's before the view.

Ideally I would have an object that tokenizes code, let's call it a token iterator, with these features:
- I can feed code to the token iterator in little chunks if I want.
- I can create a copy of the token iterator.

With just these features, I could create a token iterator and feed it everything before the top of the view **once**, and use copies of that iterator for highlighting what's currently being shown. Then editing somewhere inside the view would mean creating a new copy of the token iterator and rehighlighting the visible part of the code with that.

Python's generators have `.send()` which could be used for feeding code in chunks, but they are not copyable:

```
>>> def stupid_tokenizer(string):
...     for word in string.split():
...         yield word
... 
>>> iterator = stupid_tokenizer('bla bla lol bla lol wutz hehe')
>>> next(iterator)
'bla'
>>> import copy
>>> copy.copy(iterator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/copy.py", line 96, in copy
    rv = reductor(4)
TypeError: can't pickle generator objects
>>> 
```

Currently Pygments provides a Python generator and not much else.

**Comment by PurpleMyst** [comment]
If you're willing to use an external dependency for this, [tree-sitter](https://github.com/tree-sitter/tree-sitter) was literally made for this and it's simple, dependency-free, C

**Comment by Akuli** [comment]
this causes high cpu usage when typing into files

**Comment by Akuli** [comment]
@PurpleMyst Would you like to review #207, my ugly way to solve this problem by using a local variable inside a generator defined in pygments?
