### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Zaab1t** [Akuli/porcupine#4]
While the intended audience is beginners, I think it would be handy with some shortcuts to navigate your code faster. I don't think VIM like shortcuts fits the editor, but it here are the ones I would like:

- [x] Copy
- [x] Paste
- [x] Share
- [x] Delete current line
- [x] Move to end of line
- [x] Move to beginning of line
- [x] Move to end of file
- [x] Move to beginning of file

Since Porcupine is a Python-specific editor, we could also have Python specific keybindings like move to end of function/class and maybe end of "block" like if/try statements etc. I think we should have a little discussion before implementing anything.

**Comment by Akuli** [comment]
You can move to beginnings and ends of lines in pretty much any program, the Home and End keys are just for that. You can also use Ctrl+Home and Ctrl+End to move to beginning or end of file. Tkinter supports deleting current line with Ctrl+K by default (just like bash and readline), but we need a share/pastebin keyboard shortcut. Python-specific key bindings don't make much sense for a beginner editor IMO, but ctrl+arrow up/down for moving by two blanks could be improved a lot.

I think I should also write about this stuff in the porcupine wiki :)

**Comment by Zaab1t** [comment]
Yes a Key Bindings topic would be nice. Not all laptops have Home, End, Del, Page up and Page down. I know the new MacBook Pro doesn't and there's probably more.

**Comment by Akuli** [comment]
Thakns for letting me know, when people ask me which computer they should get for programming I'll say "anything with home and end keys" instead of "anything" from now on :)

**Comment by Zaab1t** [comment]
So key bindings/shortcuts are to be added/improved?

**Comment by Akuli** [comment]
Yes. [Here's the wiki page I wrote](https://github.com/Akuli/porcupine/wiki/Key-Cheatsheet) and [here's the code I added](https://github.com/Akuli/porcupine/commit/9c25d832461d72a60c716a143d0b1718835cf363).

**Comment by Zaab1t** [comment]
Closed for now. Might write a vim-like extension.
