### ISSUE TITLE
Feature suggestion: Draw tab into split screen

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/porcupine#406]
A nice feature found in Atom:

If you have two tabs open in porcupine, then click and drag one of them to the left/right side of the porcupine window, the two tabs open in a split screen, so you see them both next to each other.

https://user-images.githubusercontent.com/76887896/110253204-4c29ff80-7f89-11eb-86d6-74f11be79f60.mov

**Comment by Akuli** [comment]
Porcupine has this already, although the tabs become two separate windows, rather than being split within the same Porcupine window.
