### ISSUE TITLE
filetypes menu: hard to see what is selected

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#441]
If I am in a Python file, there's no checkmark or any other kind of indicator next to "Python":

![s](https://user-images.githubusercontent.com/18505570/193447198-8db42e33-6155-4737-b609-a30a89a31426.png)

This means that there's no good way to tell what filetype you currently have, and if your file is empty, no good way to notice whether changing the filetype in the menu actually did something.

Tkinter supports radiobutton menu items, which could be used to add a checkmark next to the selected filetype name.

**Comment by lawson89** [comment]
@Akuli I'll take a crack at this one

**Comment by lawson89** [comment]
@Akuli I see in the filetypes plugin's setup method the loading of the Filetypes menu
It calls menubar.add_filetab_command
I can modify this method to take an optional StringVar and if present to call add_radiobutton

But where I am struggling is how to keep this in sync. Say the user loads a new file or clicks on an unselected tab.
We would want to sync the Filetype menu option (via StringVar) to whatever the filetype of that tab right?
If so what event would I listen for and how do I get the filetype for the selected tab?

**Comment by Akuli** [comment]
Modifying `menubar.add_filetab_command()` would work, but I intended it to be a convenience thing that isn't used for anything "advanced". It's only a few lines of code, so you might as well use `menubar.get_menu()` directly.

To keep the StringVar up to date, you can use `<<NotebookTabChanged>>`. The directory tree does something similar, it always selects the current file when you switch files:

```python
get_tab_manager().bind("<<NotebookTabChanged>>", partial(_select_current_file, tree), add=True)
```

**Comment by Akuli** [comment]
> how do I get the filetype for the selected tab?

It is stored as a string `filetype_name` in the tab's settings. The settings object has a `.debug_dump()` method that shows all settings:

![d](https://user-images.githubusercontent.com/18505570/195676579-77eb80a1-f6e5-4c7d-87ce-89f81f56fc01.png)

Here I am using a debug prompt plugin that I haven't committed yet. I will make a PR that adds it in a few minutes.

**Comment by Akuli** [comment]
Debug prompt plugin is now on master. To get it onto whatever branch  you're currently on, pull from my master branch:

```
git pull https://github.com/Akuli/porcupine master
```

and then select "Run" --> "Porcupine debug prompt" in the menubar.

**Comment by lawson89** [comment]
Thanks @Akuli
