### ISSUE TITLE
old comment in default_filetypes: shift+enter --> ctrl+enter

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#442]
https://github.com/Akuli/porcupine/blob/7d8c93a45dc58f1e6c0563b907354b7897cf54db/porcupine/default_filetypes.toml#L187

**Comment by Tawishi** [comment]
hey, @Akuli this needs to be changed in the comments?

**Comment by Akuli** [comment]
Yes, the comment needs to be changed. It's a really small fix.

**Comment by Tawishi** [comment]
I would like to take this up

**Comment by Akuli** [comment]
Sure, make a pull request :)

**Comment by Tawishi** [comment]
is there only one such comment or multiple such comments exist?

**Comment by Akuli** [comment]
Here it is on master https://github.com/Akuli/porcupine/blob/master/porcupine/default_filetypes.toml#L185
