### ISSUE TITLE
plugin manager: no description available

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#478]
If you look at some plugins in plugin manager, such as black or directory_tree, it shows "(no description available)". Every plugin should have a description. The description comes from docstring of the plugin, as can be seen by `git grep`ing descriptions of other plugins.

**Comment by AvishekRoy16** [comment]
Hey boss, a noobie here looking for open source work, could you explain a bit more

**Comment by Akuli** [comment]
Sure :)

Set up and run Porcupine using developing instructions in README. Click "Settings" at top, then click "Plugin manager". If you click a plugin, you see a description of it on the right, except that sometimes it says `(no description available)`.

The goal is to figure out what each of those plugins does, and then write a description for each plugin. The plugins are files in `porcupine/plugins/`. Look at other plugins to see how the description is written to the beginning of each plugin.
