### ISSUE TITLE
multiple plugin manager windows can be open at the same time

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#485]
If a plugin manager is already open, then opening a new one shouldn't be possible. @ThePhilgrim's [minesweeper project](https://github.com/ThePhilgrim/minesweeper) has a high scores window that does this correctly, and Porcupine could use similar code.

**Comment by ThePhilgrim** [comment]
Personally, I would also prevent the plugin manager plugin from being disabled. When you disable it, there is no way to reenable it through the program (unless you reset all settings, which you might not want to do)

**Comment by Akuli** [comment]
We can add a check like "do you really want to do this".
