### ISSUE TITLE
Keypad combinations are apparently read as hotkeys and do weird stuff

### ISSUE THREAD

**Issue by Arrinao** [Akuli/porcupine#531]
Typing backslash using alt+92 on keypad opens the second tab and types the backslash into that tab, instead of whatever you have active at the time. Maybe it's just a windows issue, but it's quite annoying because backslash can only be typed by copy/pasting.

**Comment by Akuli** [comment]
For Arrinao, the solution was to disable these key bindings:

https://github.com/Akuli/porcupine/blob/02aa1075e7900f8cc124f9df4ab5cd0a6ab24ccf/porcupine/default_keybindings.tcl#L53-L56

...by adding this to Arrinao's keybindings.tcl (Edit --> Config Files):

```tcl
for {set i 1} {$i <= 9} {incr i} {
    event delete "<<TabOrder:SelectTab$i>>" <Alt-Key-$i>
}
```

On Arrinao's keyboard layout, you can also use altgr+q to type a backslash, but Arrinao didn't like it. Users are weird.
