### ISSUE TITLE
selecting "Find" text on ctrl+f

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#558]
When I press Ctrl+F, there are a couple things that I might be trying to do:
1. Type what to find or replace. To do this, it would be nice if the "Find" entry would always be emptied when Ctrl+F is pressed.
2. Search for the same thing as I was searching for last time. To do this, it would be nice if the "Find" entry would remember what was typed in. Currently this is what happens.

A good option to make both easy would be to select the text in the find area when Ctrl+F is pressed. That way I can just type new text to replace the old text for 1, or leave it in for 2.

**Comment by rdbende** [comment]
3. Search for the text, that is currently selected. I find it really useful that if something is selected, it searches for it, so I don't even have to type it

**Comment by Akuli** [comment]
Same here. New Porcupines support that, and I have no plans to ever stop supporting it. There are tests that make sure it works.

**Comment by rdbende** [comment]
Then it's great.

**Comment by Akuli** [comment]
Arrinao reported this to me. Turns out he was using Porcupine 0.92.3, and this no longer happens in 0.93.2.
