### ISSUE TITLE
Syntax colors menu is HUGE

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#710]
The syntax colors menu is so big that on linux not all items are fit on my screen (on windows the items are smaller, so it fits there). And since it sticks out completely over the menu bar when I click on that option, I immediately click on the menu item below (which is `algol`).

![image](https://user-images.githubusercontent.com/77941087/130597722-b8585780-36f5-47d9-b793-969e30138c05.png)

I tried the `columnbreak` for every 10th item but it was even worse

![image](https://user-images.githubusercontent.com/77941087/130597730-5edd184c-8c03-4d11-9c66-61a9fe51448d.png)

IMO it would be much better to have a separate window for the appearance, in which you can control both the UI theme and the syntax color. 

![image](https://user-images.githubusercontent.com/77941087/130597736-0cb68162-9778-4e6e-a8a9-b72e2c629d18.png)

a preview textbox would also come in handy for syntax colors

**Comment by Akuli** [comment]
The "Porcupine Settings" dialog is currently a bit empty. We could move both menus there.
