### ISSUE TITLE
linux installation instructions: porcu command

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#721]
If you add `export PATH="$PATH:$HOME/.local/bin"` to your `~/.bashrc`, you can type `porcu` instead of `python3 -m porcupine`. This is currently not documented.

**Comment by rdbende** [comment]
Thanks, I didn't know about that file :)

**Comment by Akuli** [comment]
It is an entry point created in setup.py:

https://github.com/Akuli/porcupine/blob/ed13a8264ccc3c222bfe52c3b3dc1389dc70d957/setup.py#L48

**Comment by Akuli** [comment]
The instructions have used `porcu` command for some time now.
