### ISSUE TITLE
cannot copy/paste from passive text widgets

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#813]
Would be nice to copy/paste output of running command within porcupine window. Affects everything that uses `textutils.create_passive_text_widget()`.

**Comment by rdbende** [comment]
I can't figure out, how to do it. Can't bind it as it can't be in focus

**Comment by Akuli** [comment]
Apparently `takefocus=True` is enough. For example:

```
>>> from porcupine.textutils import create_passive_text_widget
>>> t = create_passive_text_widget(None)
>>> t.pack()
>>> t['state'] = 'normal'
>>> t.insert('end', 'asdf')
>>> t['state'] = 'disabled'
>>> import tkinter
>>> tkinter.Entry().pack()
>>> t['takefocus'] = True
```

After running the last line, it is possible to switch between the entry and the text widget using tab. It is also possible to copy the text.

To get Ctrl+A to select all in the text widget, like you would expect it to do, you can load default_keybindings.tcl:

```
>>> t.tk.eval('source porcupine/default_keybindings.tcl')
''
```

**Comment by Akuli** [comment]
Turns out that the run plugin doesn't use `textutils.create_passive_text_widget`, but it should be changed to use it.
