### ISSUE TITLE
Dialog for choosing directory (Open File) consumes click event

### ISSUE THREAD

**Issue by nicolafan** [Akuli/porcupine#820]
### Problem
![Schermata da 2021-10-04 14-15-34](https://user-images.githubusercontent.com/48762613/135849703-5b0952de-96d3-4e1c-81ba-d093a50d50d2.png)
When the dialog for choosing a directory opens on top, in the moment it gets opened, the mouse click event used to open it gets consumed by the dialog that chooses the directory which happens to be under the mouse pointer.

### How to reproduce
Tested on Ubuntu 21.04.
File > Open > Click on the selector beside "Directory:" (when clicking put the mouse pointer slightly on top of the bottom border of the selector).

**Comment by Akuli** [comment]
Unfortunately this isn't something we can fix in Porcupine.

Porcupine uses `tkinter.filedialog` for this, which calls [tk_getOpenFile](https://www.tcl.tk/man/tcl8.4/TkCmd/getOpenFile.html). On Windows and MacOS, it uses their native file dialogs. On Linux it has its own file dialog implementation, which has this bug.

If you want it fixed, report it to Tcl/Tk issue tracker, along with minimal Tcl code for them to run (so they don't have to write Porcupine, which uses tkinter, which uses Tcl/Tk). Here is Tcl code to reproduce the problem:

```tcl
package require Tk
tk_getOpenFile
```
