### ISSUE TITLE
run plugin mac

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#824]
I don't have a Mac, and I don't know whether run plugin works on mac.

How to verify if it works:
1. Create new file
2. Write `print(123)` into it
3. Save as `something.py`
4. Press F4. By default, it should have command set to `python3 {file_name}`, folder set to `{folder_path}` and "Use an external terminal window" selected.
5. Click "Run". A new terminal window should appear with 123 in it, then a message asking to press Enter to close the window.
6. Repeat but choose "Display the output inside the Porcupine window" instead of "Use an external terminal window".

The code that opens a terminal window has been modified a lot since it was tested last time.

https://github.com/Akuli/porcupine/blob/d87c1ce1d20f6bb1d7c12c7138e0bddc12444c86/porcupine/plugins/run/terminal.py#L51-L52

@1anakin20 would you like to have a look? :)

**Comment by 1anakin20** [comment]
Surely! I'll test it on my Mac and tell you the results

**Comment by 1anakin20** [comment]
It works fine. Both the external window and the embedded window.

**Comment by Akuli** [comment]
Awesome!
