### ISSUE TITLE
about dialog links

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#825]
The about dialog (Help -> About Porcupine) says "Porcupine is installed to", and then there is a path. Clicking the path should open that folder.

@1anakin20 can you test this too? :D

**Comment by 1anakin20** [comment]
Yes, I'll test on my Mac.

**Comment by 1anakin20** [comment]
This works fine. The full path shows correctly and clicking it opens a finder window of the folder.

**Comment by Akuli** [comment]
Thanks!
