### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#998]
![anhuge](https://user-images.githubusercontent.com/18505570/144142891-6a9a4305-f836-4a6b-be18-35737b38d8bb.png)

an huge

**Comment by Moosems** [comment]
Location of code?

**Comment by rdbende** [comment]
It's here:

https://github.com/Akuli/porcupine/blob/e94f8e6fc5a5330ddb6c1653acd10067b984329c/porcupine/tabs.py#L173

**Comment by rdbende** [comment]
By the way, if you use Git, you can simply search for such things with `git grep`.

```bash
git grep "an huge"
```

**Comment by Moosems** [comment]
Since I use a Mac it's difficult to set up porcupine (it won't run) so I've been doing my edits and searching in the GitHub editor and viewer

**Comment by Akuli** [comment]
Porcupine should work on mac. I know at least one mac user who has contributed to Porcupine before. If you get an error, can you post it here?

**Comment by Moosems** [comment]
Yeah. It's just import errors that I can't figure out

**Comment by Moosems** [comment]
I'll post em in a few

**Comment by Moosems** [comment]
@Akuli 
```yaml
Traceback (most recent call last):
  File "/Users/Moosems/Downloads/porcupine-master/porcupine/__main__.py", line 6, in <module>
    from porcupine import __version__ as porcupine_version
ModuleNotFoundError: No module named 'porcupine'
```

**Comment by Akuli** [comment]
- What command are you using to run porcupine? You should use `python3 -m porcupine` inside `/Users/Moosems/Downloads/porcupine-master`.
- If you didn't already, you need to create and activate a venv.
- You might want to use git instead of downloading Porcupine as a zip file.

There's commands for doing all this in the README, in the "Developing Porcupine" section.

**Comment by Moosems** [comment]
Oh my goodness this is epic
